### ISSUE TITLE
Unable to go back from map page after using 'destination=...' parameter

### ISSUE THREAD

**Issue by maurizi** [azavea/cac-tripplanner#1015]
Steps to reproduce:

 - Got to `https://gophillygo.org/?destination=39.952691343216124%2C-75.14891230525465&destinationText=National%20Constitution%20Center`
 - The URL will be changed to `https://gophillygo.org/?origin=&originText=&mode=TRANSIT%2CWALK&maxWalk=482802&wheelchair=false&bikeOptimize=GREENWAYS&arriveBy=false&dateTime=&destination=39.9526913%2C-75.1489123&destinationText=National%20Constitution%20Center`
 - Attempt to use the browser Back button to leave the page - you will not go to your previous page but instead be forced to remain on the current page, with the map location re-centered.

This is likely due to using `Location.assign()` when we should be using `Location.replace()`

**Comment by flibbertigibbet** [comment]
This project uses [Navigo](https://github.com/krasimir/navigo) for routing, and so does not directly manipulate `Location`.

**Comment by flibbertigibbet** [comment]
Blocked by #1024

**Comment by flibbertigibbet** [comment]
Do as part of #1024
