### ISSUE TITLE
Investigate potential travelshed error

### ISSUE THREAD

**Issue by jcahail** [azavea/cac-tripplanner#1017]
In Explore mode, using bike, CAC staff member input 200 Market St. as the origin, within 60 mins, and got an error.

<img width="1042" alt="no_travelshed" src="https://user-images.githubusercontent.com/24727081/37975688-dd697c5a-31ad-11e8-9181-30fc7085ee7c.PNG">

**Comment by flibbertigibbet** [comment]
Have not been able to reproduce.

![image](https://user-images.githubusercontent.com/960264/37976554-be2491ca-31af-11e8-9609-9f4a055a9bf9.png)

**Comment by jcahail** [comment]
Change the mode to bike. It took me a bit, but I was able to reproduce it.

Jessica Cahail, Project Manager

Azavea |  990 Spring Garden Street, 5th Floor, Philadelphia, PA
jcahail@azavea.com <jbranigan@azavea.com>  | T 215.701.7722  | F
215.925.2663
Web azavea.com <http://www.azavea.com/>  |  Blog azavea.com/blogs
<http://www.azavea.com/Blogs>  | Twitter @azavea <http://twitter.com/azavea>

**Comment by flibbertigibbet** [comment]
Isochrone build for one hour travel radius with transit and bike modes currently takes ~160 seconds locally, well beyond the 30 second nginx/gunicorn timeout.
