### ISSUE TITLE
Site error

### ISSUE THREAD

**Issue by jcahail** [azavea/cac-tripplanner#1039]
500 error on the site if you click on any of the events or destinations

<img width="639" alt="capture" src="https://user-images.githubusercontent.com/24727081/39310817-6ac80db2-4939-11e8-8399-360dbaedf055.PNG">

**Comment by flibbertigibbet** [comment]
Closed in https://github.com/azavea/cac-tripplanner/commit/7ba81a90c8076df00d12126de70b7ffadd5e366a.
