### ISSUE TITLE
Determine what is increasing App Server ASG desired capacity

### ISSUE THREAD

**Issue by tnation14** [azavea/cac-tripplanner#1063]
The App Server ASG has a desired capacity of 2, even though `default.yml` uses the default value of 1.  Determine what's triggering the increase in ASG desired capacity, and ensure that the ASG desired capacity remains at 1.

**Comment by hectcastro** [comment]
Two things I noticed while looking at the stack:

- There is an old ASG and launch configuration that appears to no longer be in use (from December 2016); we should delete them
- The active web ASG has auto scaling configured based on network activity; the active OTP ASK has it configured based on CPU

If we don't have a great sense for how to configure auto scaling for these servers, or we think that it isn't necessary, we should just remove the policies in the CloudFormation configuration.

**Comment by flibbertigibbet** [comment]
Autoscaling is valuable for this site and has behaved correctly in the past during traffic surges; the issue here seems to be a configuration with an incorrectly set minimum that somehow overrode what was deployed with the `default.yaml` configuration that should have been used instead.

**Comment by hectcastro** [comment]
The CloudFormation stack parameters for the ASG in `WebServerStack-f88a45c81a4ffc6a3` were:

- `ASGDesiredCapacity = 1`
- `ASGMaxSize = 6`
- `ASGMinSize = 1`

Based on the configured ASG scaling policies, the desired capacity is set to:

- Increase by 1 if `NetworkOut >= 10000000 for 1 consecutive period of 300 seconds`
- Decrease by 1 if `NetworkOut < 500000 for 3 consecutive periods of 300 seconds`

Based on the last ~5 days of metrics for the ASG, we'd have to set the scale down threshold to ~2MB (vs. .5MB) for it to realistically take effect after 3 consecutive 5 minute periods:

<img width="1402" alt="screen shot 2018-08-13 at 16 07 06" src="https://user-images.githubusercontent.com/43639/44055325-16cc00da-9f13-11e8-9866-9d821c8dea51.png">
