### ISSUE TITLE
App not fetching updated end date for multi-day event

### ISSUE THREAD

**Issue by jcahail** [azavea/cac-tripplanner#1065]
The Parks on Tap end date (for this weekend, at Dickinson Square Park) is listed as the 13th (which is what CAC originally published). After realizing the end data is actually the 12th, CAC staff un-published and re-published the event listing with the corrected date, but it is not reflected on the app.

**Comment by flibbertigibbet** [comment]
On the website:

![image](https://user-images.githubusercontent.com/960264/43781449-e6b830f4-9a2a-11e8-84d5-98b70e8f399a.png)

**Comment by flibbertigibbet** [comment]
If by "the app" they mean the mobile application, its repository is [over here](https://github.com/azavea/cac-tripplanner-android). The mobile application caches server information in production builds for 12 hours to save data, so modification will not be reflected immediately there.
