### ISSUE TITLE
Upgrade development environment to PostgreSQL 9.4

### ISSUE THREAD

**Issue by CloudNiner** [azavea/cac-tripplanner#1079]
The production database is currently running PostgreSQL 9.3, which is losing support in AWS RDS on Sept 5, 2018. On or nearly after Nov 1, 2018, AWS will auto-upgrade any remaining RDS instances still on 9.3 to the latest 9.4 bugfix release. This task is to upgrade the DB to at least the latest 9.4 bugfix release before the Nov 1 deadline. If time/budget allows, we could explore bumping to 9.6 or higher.

More complete details from AWS:

> As part of the retirement plan for Amazon RDS PostgreSQL 9.3, we have disabled creation of any new PostgreSQL 9.3 instances using the AWS console. Starting September 5th, 2018, we will start to disable new PostgreSQL 9.3 instance creation using the CLI/API. We anticipate the process to complete by September 30th, 2018. You can continue to do PostgreSQL 9.3 restores and read replica creations until October 31st, 2018.  In November 2018, your remaining 9.3 instances will be force upgraded to the most recent minor version of PostgreSQL 9.4. Once this occurs, any instance restored from a snapshot of a deprecated version will automatically and immediately be upgraded to a currently supported version. 

- https://www.postgresql.org/support/versioning/
- https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html
- https://aws.amazon.com/support
- https://aws.amazon.com/rds/faqs/ [search for “guidelines for deprecating database engine versions”]

**Comment by CloudNiner** [comment]
It also looks like we missed the original six month announcement. From [the FAQs](https://aws.amazon.com/rds/faqs/):

> When a major version of database engine is deprecated in Amazon RDS, we will provide a minimum six (6) month period after the announcement of a deprecation for you to initiate an upgrade to a supported major version. 

We should take a look at our notification settings (email, etc) to make sure we're receiving these communications to a place where we can take action on them.

**Comment by hectcastro** [comment]
As part of upgrading PostgreSQL, confirm the versions of PostGIS available on PostgreSQL 9.4 and make them consistent in development.
