### ISSUE TITLE
Upgrade staging environment to PostgreSQL 9.4

### ISSUE THREAD

**Issue by hectcastro** [azavea/cac-tripplanner#1080]
- Execute an in-place upgrade via the console
- Update the PostgreSQL version strings in CloudFormation (just to maintain consistency)
- Upgrade PostGIS using

```sql
ALTER EXTENSION POSTGIS UPDATE TO '...'
```

For all of the specific steps, see: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html

**Comment by rbreslow** [comment]
@hectcastro Do you want to schedule time to pair on this next week?

**Comment by hectcastro** [comment]
Might be good to defer until after Kathryn gets a chance to run through the app in development to ensure that there aren't any regressions. I added her as a reviewer to the development env PR so that she can start that process once it is in a good state.
