### ISSUE TITLE
`TypeError: Cannot read property 'length' of undefined` on some detail pages

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#1118]
Following error appears in the console on _some_ detail pages, including:
- https://gophillygo.org/place/57/
- https://gophillygo.org/place/117/

```js
Uncaught TypeError: Cannot read property 'length' of undefined
    at N (vendor.js:1)
    at HTMLDocument.<anonymous> ((index):350)
    at u (vendor.js:1)
    at c (vendor.js:1)
```

**Comment by flibbertigibbet** [comment]
It appears to be the new carousel library attempting to initialize on a page without a carousel, but a single image. This probably isn't breaking any functionality, but should be addressed.
