### ISSUE TITLE
Specialize cards for tours and events

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#1146]
Cards on the home page and map sidebar for tours and events should:
 - present images in a carousel pulled from their available destinations
 - ~link to tour/event map overview page instead of directions to the first destination~
 - 'Directions' card link should be labelled 'Map' instead for (non-routable) event map overview

(Note screenshot shows 'Map' link for tours, but that should be for events.)
![image](https://user-images.githubusercontent.com/960264/65057079-049c5780-d940-11e9-9a49-d06532f52c54.png)

**Comment by KlaasH** [comment]
Is the carousel treatment supposed to apply to both tours and events, or just tours?  You wrote both, and it would be possible to show a destinations carousel for both, but events also have their own images, so I'm not sure how those would interact with the destination images.  It seems like it might be less clear to have the whole set (event images + destination images) than to just show the first event image, as we're currently doing.

The wireframes show a carousel on both the home page and the explore sidebar for tours, but show no carousel on the home page for events:
![image](https://user-images.githubusercontent.com/6598836/66080433-1848e000-e534-11e9-870f-f0bd93a26345.png)

There's no wireframe showing event cards on the explore view, but I would assume they should look the same as on the home page.

**Comment by flibbertigibbet** [comment]
Let's go with the wireframes and just add the carousel for tours.

**Comment by flibbertigibbet** [comment]
Closed in #1150
