### ISSUE TITLE
Change directions link to "Map" for tour cards

### ISSUE THREAD

**Issue by KlaasH** [azavea/cac-tripplanner#1152]
This was part of issue #1146 but not included in PR #1150. Per my comment there:
> The other task from the issue is 
>> "'Directions' card link should be labelled 'Map' instead for (non-routable) event map overview" 
> 
> This is the same thing as the link on the Tour Detail page, but there's currently only a back-end function for composing it. To get it working in the front-end version of the templates, we need to either write a front-end tag to reproduce the behavior or stuff that link into the API response. I was leaning toward the latter, since it's a fairly involved bit of business, but I'm wondering what you think would be best.

After looking at it a little more, I still think composing the link once, on the back-end, and sending it along with the API response seems like the way to go.

**Comment by flibbertigibbet** [comment]
I intended this task to only be to alter the text in the link between 'map' and 'directions', not the directions link itself, which has been handled separately.

**Comment by KlaasH** [comment]
Oh, ok.  That's much easier.  I was looking at the existing "Tour Map" link from the tour detail page and thinking that same link would have to be recreated, but I see that clicking the existing Directions link on a Tour card does indeed get you to the same view.  Cool.

**Comment by flibbertigibbet** [comment]
Closed in #1154
