### ISSUE TITLE
Clicking "See All" on tour/event detail page should land on appropriate tab

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#1169]
When on a tour or event detail page, clicking the "See all…" button at the bottom of the page lands on the home page All tab, rather than {Tours, Events} tab.

**Comment by flibbertigibbet** [comment]
We don't immediately have a way to deep-link to a filter on the home page.

**Comment by lederer** [comment]
Ok. I'll remove the See All buttons from the event and tour detail pages.

**Comment by flibbertigibbet** [comment]
Closed in #1182.
