### ISSUE TITLE
Show per-location times on place cards in multi-location event map view

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#1172]
When a multi-location event has per-location timing, each location's time should be rendered on its place card in the event map view. See mockup.

**Comment by lederer** [comment]
![image](https://user-images.githubusercontent.com/128699/66952166-10a43380-f02a-11e9-9274-933a56074fa8.png)

**Comment by flibbertigibbet** [comment]
Closed in #1177.
