### ISSUE TITLE
Refreshing mobile tour does not initiate carousel

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#1201]
On mobile, navigate to a tour map. Refresh browser. Locations are in a normal flow layout rather than arranged in a carousel. The tiny-slider wrapper elements are not present in the DOM.

This affects tours and multilocation events, but does **not** affect direction itineraries.

![image](https://user-images.githubusercontent.com/128699/67978893-7b8c6780-fbf1-11e9-9df5-4d1a9c32d527.png)

**Comment by flibbertigibbet** [comment]
When this happens, there are two `.tour-list` results in the DOM (there should only be one).

**Comment by flibbertigibbet** [comment]
Requires production JS build to reproduce (npm run gulp-production).

**Comment by flibbertigibbet** [comment]
Closed in #1234.
