### ISSUE TITLE
Upgrade production database

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#1239]
The production database is currently on PostgreSQL 9.4, which is approaching end of life. The final release for 9.4 is planned for [February 2020](https://www.postgresql.org/support/versioning/).

Upgrade the database to 9.5 or later (9.6 has been working in development).

**Comment by hectcastro** [comment]
- [ ] Upgrade the development environment to PostgreSQL 9.6; ensure the application functions as expected
- [ ] Upgrade the staging environment to PostgreSQL 9.6 (and ensure that the appropriate client libraries are baked into the release artifact
- [ ] Upgrade the production environment to PostgreSQL 9.6, coupled with a production release with the upgraded PostgreSQL client libraries

See: https://azavea.slack.com/archives/C0B2YCH0W/p1575477400020900
