### ISSUE TITLE
Add support for Dependabot and GitHub Security alerts

### ISSUE THREAD

**Issue by hectcastro** [azavea/cac-tripplanner#1269]
This project contains dependencies that span multiple supported Dependabot ecosystems (e.g., NPM, Python). Wire up Dependabot via `dependabot.yml` such that all relevant dependencies supported are managed and upgraded as new releases exist.

See: https://github.com/azavea/operations/blob/main/.github/dependabot.yml

**Comment by BryanQuigley** [comment]
New style depenabot is enabled.
