### ISSUE TITLE
Resolve "Copy Built OTP Graph to Host" error in provisioning

### ISSUE THREAD

**Issue by ddohler** [azavea/cac-tripplanner#1301]
When provisioning the OTP VM from scratch, an error is sometimes raised on the "Copy Built OTP Graph to Host" step. This error prevents the application from being deployed properly.

So far, the error has only occurred for Mac users, but it's unclear whether it is a Mac-specific issue or whether it could be an issue with Vagrant / Virtualbox / Ansible versions.

The specific error message given in these cases is:
```
ssh: Could not resolve hostname otp: nodename nor servname provided, or not known
rsync: connection unexpectedly closed
```

**Comment by rachelekm** [comment]
This issue is resolved through edits made to the GoPhillyGo deployment doc in [PR #257 in azavea/geospatial-apps](https://github.com/azavea/geospatial-apps/pull/257).
