### ISSUE TITLE
Investigate usage of production group_vars AWS keys 

### ISSUE THREAD

**Issue by ktohalloran** [azavea/cac-tripplanner#1310]
The AWS Access Key ID and Secret Access Key ID listed in `production` `group_vars` in LastPass do not match the existing keys for the Azavea account. A quick investigation suggests that these keys are not used by the app in production. We need to investigate whether these keys are used and then, based on findings, either replace or remove them.

**Comment by ddohler** [comment]
As part of our running credentials audit I've confirmed that these credentials are unused and that the values we had were non-functional in any case, so I've removed them.
