### ISSUE TITLE
Assess need / cost to migrate to Google Analytics 4

### ISSUE THREAD

**Issue by ddohler** [azavea/cac-tripplanner#1329]
Google Analytics announced that the current version of Analytics will be [switched off in a little over a year](https://support.google.com/analytics/answer/10759417), so we should assess where Analytics is used in the app and make issues covering the necessary tasks to switch. We should assess both the Android app and the web app. The deliverable for this task is a summary of the status and necessary migration steps, and any issues necessary to reflect those tasks.

**Comment by BryanQuigley** [comment]
They didn't give many options in the way of testing it out - without actually just doing it.
