### ISSUE TITLE
make layer switcher collapsable

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#133]

**Comment by CloudNiner** [comment]
This is not trivial AFAIK, the leaflet options are always open, or expandable on hover. But I didn't look into it too much.

**Comment by flibbertigibbet** [comment]
How about [this layer control](https://github.com/vogdb/SelectLayersControl)? @mtedeschi

**Comment by flibbertigibbet** [comment]
Maybe this [collapsible panel control](http://labs.easyblog.it/maps/leaflet-panel-layers/examples/collapsible-panel.html) might work. @mtedeschi

**Comment by flibbertigibbet** [comment]
Closed in #244, but needs styling work.
