### ISSUE TITLE
Run PostgreSQL upgrades locally & in new testing environment

### ISSUE THREAD

**Issue by rachelekm** [azavea/cac-tripplanner#1374]
This card is to setup a testing environment created from a snapshot of our production RDS instance, and then run upgrades locally and in testing environment. These two tasks will allow us to gain familiarity with the production database upgrade steps and ensure no issues for #1375.

The last PostgreSQL update was completed by first testing on develop and then running updates on the Production database. See [step-by-step here](https://github.com/azavea/cac-tripplanner/issues/1298#issuecomment-1014865329). There shouldn't be difficulties between versions given the last few PostgreSQL upgrades and available documentation. However, we have limited developer familiarity with production database updates, last run 2 yeas ago, and at one point our development environment had gotten out of sync with our RDS environment (though this should have been addressed in last update). In addition, we are upgrading Python versions, `psycopg2`, and PostGIS as part of #1372 task list. Given scope of upgrades and a potential lack of parity and familiarity, a temporary staging database made from a duplicate of production to run upgrades will lower risk and production downtime.

**Comment by rajadain** [comment]
Staging upgrade to be done in #1388.
