### ISSUE TITLE
Update RDS SSL/TLS certs

### ISSUE THREAD

**Issue by rachelekm** [azavea/cac-tripplanner#1386]
The current certificate used to secure database communications expires August 22, before that date we need to update the RDS SSL/TLS certs.

<img width="1472" alt="Screenshot 2024-08-15 at 8 01 53 AM" src="https://github.com/user-attachments/assets/b50f177e-0425-443b-98c5-c51845af40f0">
<img width="1473" alt="Screenshot 2024-08-15 at 8 05 00 AM" src="https://github.com/user-attachments/assets/57ae73f3-0812-40a1-824a-ba265d11ae1c">

**Comment by JN-Hernandez** [comment]
# WorkPlan Template

## Summary

An email notification was received regarding expiring RDS certs:
> You are receiving this message because your AWS Account has one or more Amazon RDS, or Amazon Aurora database instances in the US-EAST-1 Region using a SSL/TLS Certificate that is expiring on August 22, 2024.

As such, we will need to update the RDS SSL/TLS certs prior to Aug 22, 2024.

### Preliminary Investigation

- [x] 1. Review CloudFormation to determine if RDS certs are handled through CloudFormation
	- [data.py](https://github.com/azavea/cac-tripplanner/blob/develop/deployment/cloudformation/data.py) file indicates we do not set any specific `CAIdentifier`

- [x] 2. Review [AWS Documentation: Rotate Your SSL/TLS Certificates Now - Amazon RDS and Amazon Aurora Expire in 2024](https://aws.amazon.com/blogs/aws/rotate-your-ssl-tls-certificates-now-amazon-rds-and-amazon-aurora-expire-in-2024/)
	- Recommended updating trust store of any clients or applications that use SSQL/TLS and the server cert to connect
	- Recommended staged rollout
	- Recommended testing application post-rollout

- [ ] 3. Review of [AWS Documentation: Updating Applications to connect to PostgreSQL DB Instances using new SSL/TLS certificates](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/ssl-certificate-rotation-postgresql.html)
	- Determine whether applications are connecting using SSL
	- Determine whether a client requires cert verification in order to connect

Command to determine applications actively connected using SSL:
```
SELECT datname, usename, ssl, client_addr 
  FROM pg_stat_ssl INNER JOIN pg_stat_activity ON pg_stat_ssl.pid = pg_stat_activity.pid
  WHERE ssl is true and usename<>'rdsadmin';
```

Command to determine whether client requires certificate verification to connect:
```
PGSSLMODE=verify-full PGSSLROOTCERT=/fullpath/ssl-cert.pem psql -h tankmagic-staging.csi1vuilpobj.us-east-1.rds.amazonaws.com -U masteruser -d postgres
```

```
psql "host=tankmagic-staging.csi1vuilpobj.us-east-1.rds.amazonaws.com sslmode=verify-full sslrootcert=/full/path/ssl-cert.pem user=masteruser dbname=postgres"
```

- [ ] 4. Check size of the database to help determine size of impact

```psql
\l+
```
## Steps

### Pre-Implementation

- [ ] 1. Notify client concerning downtime
	- Handled by @(user) on (date)

- [ ] 2. Add the `staging` and `production` DB user and password information to 1Password
	- [ ] Staging: 
	- [ ] PROD: 

- [ ] 3. Update external IP address
	- If needed

### Implementation

- [ ] 1. Review certificate to confirm it points to the old certificate `rds-ca-2019`
	- Staging DB Identifier: 
	- PROD DB Identifier: 

```shell
aws rds describe-db-instances --db-instance-identifier <db_identifier> | grep CACertificateIdentifier
```

- [ ] 2. Modify the DB instance to the new cert `rds-ca-rsa2048-g1`

```bash
aws rds modify-db-instance \
          --db-instance-identifier <db_identifier> \
          --ca-certificate-identifier rds-ca-rsa2048-g1 \
          --apply-immediately
```

- [ ] 3. Review the AWS RDS Database UI to view database status - confirm returns to `Available`

```shell
aws rds describe-db-instances --db-instance-identifier <db_identifier> | grep DBInstanceStatus
```

### Post-Implementation

- [ ] 1. Set the default RDS certificate to `rds-ca-rsa2048-g1` - this ensures new database creations use the correct certificate when deployed

```bash
aws rds modify-certificates \
          --certificate-identifier rds-ca-rsa2048-g1 \
          --region us-east-1
```


## Criteria for Success

- [ ] 1. Confirm able to connect to the database post implementation

Connect to the `bastion` host
- Staging 1Password Entry: 
	- Staging Bastion IP: 
- PROD 1Password Entry: 
	- PROD Bastion IP: 

```
# Connect to the VPN
# Download the appropriate PEM file from 1Password
chmod -400 <pem_file>
ssh -i <path/to/file.pem> ec2-user@<bastion_IP>
```

Connect to the `database` from the bastion host
- Staging 1Password Entry: 
- PROD 1Password Entry: 

> [!Note]
> The `PSQL` connection string for the database is within the `Notes` section of the 1Password entry.  You will be prompted for the password.

- [ ] 2. Confirm the application works as expected post-implementation
	- Traverse to the site
	- Perform hard refreshes
	- Check the database connections and confirm SSL shows `t` (True)

```
SELECT datname, usename, ssl, client_addr 
  FROM pg_stat_ssl INNER JOIN pg_stat_activity ON pg_stat_ssl.pid = pg_stat_activity.pid
  WHERE usename<>'rdsadmin';
```
## Risk

**High Risk** - this change will require database downtime and any connections that use SSL will need to be updated.

1. Any connections to the database that use SSL and are not updated will no longer be able to connect.
2. Failure to implement this change will result in certificate expiration on Aug 22, 2024, resulting in SSL connection failures.

## Rollback

- [ ] 1. Perform **Implementation** steps, updating the certificate back to `rds-ca-2019`

```bash
aws rds modify-db-instance \
          --db-instance-identifier <db_identifier> \
          --ca-certificate-identifier rds-ca-2019 \
          --apply-immediately
```

## Additional Details

- [AWS Documentation: Rotate Your SSL/TLS Certificates Now - Amazon RDS and Amazon Aurora Expire in 2024](https://aws.amazon.com/blogs/aws/rotate-your-ssl-tls-certificates-now-amazon-rds-and-amazon-aurora-expire-in-2024/)
- [AWS Documentation: Updating Applications to connect to PostgreSQL DB Instances using new SSL/TLS certificates](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/ssl-certificate-rotation-postgresql.html)
- [AWS Documentation: AWS::RDS::DBInstance CertificateDetails](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-dbinstance-certificatedetails.html)
- Paired with @(user) to confirm application connectivity

**Comment by JN-Hernandez** [comment]
Paired with @rachelekm on this change, the only issue that arose was the PHL VPN was down and we had to use the ALX VPN instead.  This prompted us to edit the `sgBastion` security group manually and temporarily to include the inbound rule for the ALX External IP:
```
Port: 22
IP: 208.253.124.211
```

Test proved successful and we backed out the security group change.
