### ISSUE TITLE
Map page refresh on options changed

### ISSUE THREAD

**Issue by jbranigan** [azavea/cac-tripplanner#155]
We should update the map as users tweak settings - both for directions and isochrone (within reason).

**Comment by flibbertigibbet** [comment]
It might be difficult to handle debouncing appropriately; there are a bunch of different inputs the user can fiddle with before they're ready to go query, OTP responses can take many seconds to come back, and there's no cancelling a request once it's sent off, so it might be easy to overload OTP with requests.

Maybe we could try a more obvious 'go' button?

**Comment by jbranigan** [comment]
Definitely a challenge to find the right balance - this is going to require some conversation and testing.

**Comment by jbranigan** [comment]
This is working way better than before. I can still destabilize things, though. Let's take a closer look at what's going on and tune it a bit.
