### ISSUE TITLE
Cartography enhancements

### ISSUE THREAD

**Issue by jbranigan** [azavea/cac-tripplanner#156]
*   Isochrone style
*   Primary/secondary directions lines styles
*   Icons
*   Basemap options

**Comment by jbranigan** [comment]
This is for the isochrone and directions lines...

Solid Line:
stroke-linejoin="round" stroke-linecap="round" stroke="#d02d2d" stroke-opacity=".75" stroke-width="5" fill="none"

Dash Line:
stroke-linejoin="round" stroke-linecap="round" stroke="#2c7fb8" stroke-opacity=".75" stroke-width="5" stroke-dasharray="5, 8" fill="none"

Isochrone Blob
stroke-linejoin="round" stroke-linecap="round" fill-rule="evenodd" stroke="#5c2482" stroke-opacity="0.4" stroke-width="2" fill="#5c2482" fill-opacity="0.3"

**Comment by flibbertigibbet** [comment]
The [Leaflet GeoJSON styling options](http://leafletjs.com/reference.html#path-options) don't have a `fill-rule`, and `fill` doesn't apply for lines, but otherwise these styles should work well.

**Comment by jbranigan** [comment]
Cool. I'm reopening to account for icon and basemap changes, unless you'd prefer I open new issues for those.

**Comment by jbranigan** [comment]
For featured location icons, any preferences on one of these three? I'm partial to the first one.

![](http://google.github.io/material-design-icons/maps/svg/ic_beenhere_24px.svg)
![](http://google.github.io/material-design-icons/maps/svg/ic_local_attraction_24px.svg)
![](http://google.github.io/material-design-icons/maps/svg/ic_satellite_24px.svg)

Featured location icon color can be the same green we used for Indego.
Let's change Indego icons to #0083CC. That's the light blue from their logo.

Still more ideas to come, this is still WIP...

**Comment by flibbertigibbet** [comment]
The [FontAwesome markers](https://github.com/lvoogdt/Leaflet.awesome-markers) we're using use png images for the markers, so we're limited in the available colors.  There's 'blue' and 'cadetblue' available; their 'blue' is pretty close.

**Comment by jbranigan** [comment]
The 'blue' looks pretty good to me.

**Comment by jbranigan** [comment]
Can we switch out the Stamen base maps for CartoDB's positron and dark matter? Positron would be the default. In the layer switcher, we can just call the layers "light" and "dark"

**Comment by jbranigan** [comment]
All looks good
