### ISSUE TITLE
Add default active classes to tabs

### ISSUE THREAD

**Issue by jbranigan** [azavea/cac-tripplanner#157]
On home page in hero, tabs at top of map sidebar

**Comment by flibbertigibbet** [comment]
Could you clarify which tabs?  The map page tab toggle buttons and their associated sidebar sections have the active class set/unset on them already, as well as the toggle-able buttons on the home page.

**Comment by jbranigan** [comment]
When I go to the homepage, the two buttons are the same color. Users saw this first upon hitting the page and didn't know what to do.

@mtedeschi mentioned the tabs - want to clarify, Mike?

**Comment by kshepard** [comment]
I can reproduce these if I clear my local storage. It's only on the first viewing, before your settings are stored. Should be a very easy fix, I'll take a quick look.

**Comment by flibbertigibbet** [comment]
Oh, okay.  Yeah, the home page should set the default tab active then.
