### ISSUE TITLE
Add "x" to clear text inputs

### ISSUE THREAD

**Issue by jbranigan** [azavea/cac-tripplanner#164]
It looked like a lot of work to select the whole string and delete it (often extends beyond the length of the text box).

**Comment by flibbertigibbet** [comment]
Just noticed Internet Explorer adds text box clearing x's by itself.

**Comment by jbranigan** [comment]
IE is so cool. So if we add our own, it'll break, I'm guessing...

**Comment by flibbertigibbet** [comment]
Can change the input type to "search" and HTML5 should add an `x` to clear.  However, we have our own search magnifying glass icon on the right already, so the `x` doesn't show.

**Comment by flibbertigibbet** [comment]
Changing `type` to `search` doesn't show the HTML5 clear button; possibly a styling issue.
