### ISSUE TITLE
Windows Chrome and Firefox sidebar formatting

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#194]
In 'Discover Places' tab, 'View more options' is not visible (cut off at bottom of section.)

**Comment by mtedeschi** [comment]
Looks like this might have been fixed in the latest batch of styling updates. I'm leaving it open, but can you confirm that this was fixed or provide a screenshot of where it looks wrong?

**Comment by flibbertigibbet** [comment]
Yes, looks to be fixed now on Windows/Chrome and Windows/Firefox.
