### ISSUE TITLE
Adjust sizes/dimensions for Django article images

### ISSUE THREAD

**Issue by mtedeschi** [azavea/cac-tripplanner#231]
Wide image
Minimum size: 1280x400 pixels

Narrow image
Minimum size: 400x600 pixels (this is good as-is)

**Comment by jbranigan** [comment]
Update with actual numbers sent to the design company:

*   For the homepage hero area, that image should be at least 1440x650px.
*   For the large article hero image, that should be at least 1440x400px.
*   For the small thumbnail article image, that should be at least 400x600px.
*   For destination thumbnails, that should be at least 400x400px.

**Comment by kshepard** [comment]
Closed via #300
