### ISSUE TITLE
Add "View All" page template for articles

### ISSUE THREAD

**Issue by mtedeschi** [azavea/cac-tripplanner#232]
Unless I just don't see it, we need to create a page template to show all articles on a single page. We might need pagination or lazy loading to show all of them once it starts getting longer. We should wire this up to the "View all" link on the homepage.

**Comment by flibbertigibbet** [comment]
As a side note, the "View All" link for featured locations (which is wired up) does not paginate.

**Comment by flibbertigibbet** [comment]
"View all" for articles implemented in #253. It needs styling; there's no gap between image rows.

There's currently a limit of a maximum of the 20 most recent articles/destinations for "view all."

**Comment by mtedeschi** [comment]
So we decided to implement this as a load more type thing instead of another page?

**Comment by flibbertigibbet** [comment]
Given there's no template for another page for that, I've loaded them into the current page.
