### ISSUE TITLE
Directions to Valley Forge not working

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#241]
![image](https://cloud.githubusercontent.com/assets/12200440/7432276/bd823646-eff4-11e4-9fbd-ef095ee7f3f8.png)

I asked for directions from my location (CAC office) to "Valley Forge National Historic Park, N Outer Line Dr, King Of Prussia, Pennsylvania" (which was an option when I started typing Valley Forge) and the directions took me to City Hall.

**Comment by jbranigan** [comment]
Nice job on the first issue submission, @nickrogers. 

I just tried the same thing and it gave me the correct result, but initially blipped directions to City Hall before correcting. We'll dig a bit deeper.

**Comment by jbranigan** [comment]
Fixed in https://github.com/azavea/cac-tripplanner/issues/362
