### ISSUE TITLE
Suggests multimodal bike + trolley directions, current location is off

### ISSUE THREAD

**Issue by CorynWolk** [azavea/cac-tripplanner#246]
I just tested getting bike + transit directions from work to my house (which is two blocks from a trolley stop). Firstly, it shows my current location as being at 19th and Arch, not 19th and Walnut. I'm not sure what end that error is on, though. The more general issue: the website told me to bike up to the trolley station, take the trolley, and then bike the rest of the way (screenshot attached). Trolleys are (as far as I remember) the only mode on which non-folding bikes are never allowed, so this shouldn't be possible except with bike share bikes. (Incidentally, it's very simple to do bike + bus on that route, though as it's faster to just bike that distance, I don't know if the site would ever suggest it.) Can the site prevent this type of trip from being planned?

Also, I don't know if it's necessary to include the hours when bikes are allowed on SEPTA on the same page as any bike + transit trip, but it might be good to have a little warning that shows up if someone tries to plan one of those trips during a time when bikes won't be allowed on transit. (For example, bike + transit into Philadelphia from the suburbs during peak hours.) I'm not sure if that'd be too complicated, though.
![multimodal bike trolley issue](https://cloud.githubusercontent.com/assets/12202740/7436111/0a1f8850-f018-11e4-9dac-6e7232607971.jpg)

**Comment by flibbertigibbet** [comment]
* SEPTA has not defined `bikes_allowed` in their [GTFS](https://developers.google.com/transit/gtfs/reference), so by default OpenTripPlanner will allow bikes on all modes at all times.

* Location accuracy via IP address (on a non-mobile browser) will not be very accurate compared to what we're used to with mobile devices.

**Comment by CorynWolk** [comment]
Okay, I figured the location-finding issue was not a problem in the site itself, so that's good to confirm. So for the SEPTA bike issue, does that mean that the only way to prevent those directions from being created is if SEPTA  changes their GTFS?

**Comment by flibbertigibbet** [comment]
SEPTA changing the GTFS would be the easiest and best solution.  There will be similar inaccuracies around wheelchair accessibility, which due to limitations of the GTFS format, SEPTA will not be able to correct (accessibility is per-vehicle, rather than per-trip.)  The same limitation may apply to bicycle access.

**Comment by jbranigan** [comment]
For any bike / transit combo directions, we should provide a note that it is possible that bikes might not be allowed on the trip. Maybe depending on the transit system, we could provide a link to their bicycle rules page?
