### ISSUE TITLE
Route line hard to see against satellite view

### ISSUE THREAD

**Issue by CorynWolk** [azavea/cac-tripplanner#251]
Pretty self-explanatory. One of Clean Air Council's staff noted that when the map is in satellite view, the black route line is sometimes difficult to see, especially when zoomed in.

**Comment by jbranigan** [comment]
Agreed - we're in the process of changing the cartography (https://github.com/azavea/cac-tripplanner/issues/156) and will be changing some of the basemap options, too. I'm going to close this issue in favor of using 156.
