### ISSUE TITLE
Sometimes gives directions to different location if doesn't recognize address, or seems to remember/use previous destination instead

### ISSUE THREAD

**Issue by CorynWolk** [azavea/cac-tripplanner#252]
There've been a couple variations on this. This last time, I had tried searching directions from my location (found by network) to 36th and Lancaster Ave. The site didn't recognize "36th St and Lancaster Ave, Philadelphia" and tried giving me a few kind of random addresses before finally giving me directions to a point a half mile west on Lancaster Ave. I then went back to the homepage and tried getting directions to "49th St and Hazel Ave, Philadelphia." Instead, the site gave me directions to the same point on Lancaster Ave, but replaced the finish point with "49th St and Hazel Ave." (I clicked the magnifying glass a few times to try to get it to refresh the directions, but they stayed the same.)
![destination and directions mixup issue](https://cloud.githubusercontent.com/assets/12202740/7459213/5be831a8-f268-11e4-9226-4a774f4cca96.jpg)

**Comment by flibbertigibbet** [comment]
The ESRI geocoder search service (used for the suggestions) does not recognize intersections.

**Comment by jbranigan** [comment]
@CorynWolk, we spent some time last week trying to fine-tune how the location search will work. As @flibbertigibbet mentioned, this is an unsupported feature in the geocoding service. We have address, neighborhood, city, zip, featured locations, and business names, but no intersections.

**Comment by jbranigan** [comment]
We'll try to handle this a bit more gracefully, though.

**Comment by CorynWolk** [comment]
Thanks! So @jbranigan is there any workaround for that? It seems like if there's no way to get the website to recognize intersections, we should maybe make a note near the search bar instructing users not to use them. (Otherwise they might do what I did and assume it's a matter of punctuation or a random intersection not being in the database.)
