### ISSUE TITLE
Same route shown multiple times

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#256]
![image](https://cloud.githubusercontent.com/assets/12200440/7481985/4be25970-f342-11e4-9ad1-091898c7feca.png)
The same route was just repeated 3 times as my options. There should only be one option displayed if there is only one reasonable route.

**Comment by nickrogers** [comment]
![image](https://cloud.githubusercontent.com/assets/12200440/7482277/402ec3b4-f344-11e4-80df-2a7335917945.png)
The first image was after I had selected a specific bike route, so that issue is that there should only be one option leftover. This one is the initial set of directions options I get, where they repeat but I know there are other ways to get there.

**Comment by jbranigan** [comment]
The app still seems to be returning identical itineraries

**Comment by flibbertigibbet** [comment]
Could you provide an example?  Note that if there's transit involved, you may get the same route at different departure times (start time does not appear in the list view.)
