### ISSUE TITLE
Clearer state for on/off

### ISSUE THREAD

**Issue by jbranigan** [azavea/cac-tripplanner#257]
Which one is on? Which one is off? Some grey tone or some other clearer indication is required here.

![screen shot 2015-05-05 at 4 19 13 pm](https://cloud.githubusercontent.com/assets/1508618/7482024/9337b496-f342-11e4-8a5b-f16aaf34968e.png)

**Comment by nickrogers** [comment]
I was just about to leave this comment, also unclear for me.

**Comment by kshepard** [comment]
+1, I had the same confusion.
