### ISSUE TITLE
Destination information

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#259]
When clicking on a destination on the home page, the directions come up but that's it. There's no way now for me to get information on the destination. I think ideally clicking on the destination on the home page would bring me to a page with info on the destination and photos, a link to their website, etc. On there I would have a place I could click to get directions there. At a minimum, if it takes me directly to directions I should be able to get that pop up with a little info on it.

**Comment by nickrogers** [comment]
![image](https://cloud.githubusercontent.com/assets/12200440/7482299/6ff0b4b8-f344-11e4-9926-e6235e2b849a.png)

**Comment by jbranigan** [comment]
Agreed - the result should be similar to clicking a featured location on the map: it displays a photo, information, and "get directions" link, and centers the map on the location. The travelshed can be displayed here, too.
