### ISSUE TITLE
Revised homepage wireframe

### ISSUE THREAD

**Issue by WarkulwizDesign** [azavea/cac-tripplanner#265]
WDA modified the homepage skinning with readability/functionality, including:
- new logo file in white circle (in Dropbox)
- nix the blue dots, they are too busy. Change to a flat color of hex# d6effb.
- change Arvo-Bold text to Arvo-Regular. Arvo-Bold does not read as easily.
- add a line below the intro. line that says: 'There are 2 easy ways to use the map:'
![150506_gophillygo-homepage-wireframe-01](https://cloud.githubusercontent.com/assets/12275457/7521690/f1acad8e-f4bd-11e4-9ad6-81ee25160f0e.png)

**Comment by jbranigan** [comment]
Looks good. Can we change the background image with the colorful map? That was from wireframes and the site won't look like that.

**Comment by WarkulwizDesign** [comment]
Are you thinking of using the map on the current site? We liked the idea of using the map as the intro image since it is the basis of the site. The old wireframe image had the watershed areas on it which CAC liked.

**Comment by jbranigan** [comment]
The map on the current site is still in design (icons, base maps), and that should be set within the week. The travel shed is now being displayed as a single color, rather than the gradient that was in the early wireframes. For the home page, we could use a map image (once it's done) or any other image.

**Comment by WarkulwizDesign** [comment]
Okay, let's try the map image once it is done. We can always add the travelshed (sorry not watershed) areas after. For the white type to read over it, it will probably still need some sort of overlay.
