### ISSUE TITLE
Edit color of map pins

### ISSUE THREAD

**Issue by WarkulwizDesign** [azavea/cac-tripplanner#267]
Can the map pin colors be edited so that they are most distinctive - esp. for the events? The gray pin for events gets lost in the map. The start destination pin is the same color as the current bike share location. I'd suggest changing the bike share locations to the cyan color since that resonates as the color for Indego.
![wda-editmappins](https://cloud.githubusercontent.com/assets/12275457/7521873/440d3b92-f4bf-11e4-86f3-ced9e72637e7.png)

**Comment by jbranigan** [comment]
Cartography for pins and base maps is underway: https://github.com/azavea/cac-tripplanner/issues/156

**Comment by jbranigan** [comment]
And thanks for the notes!

**Comment by WarkulwizDesign** [comment]
Sorry for the repeat!!

**Comment by flibbertigibbet** [comment]
Closed with #277
