### ISSUE TITLE
Typeahead selected event always triggered twice

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#279]

**Comment by mtedeschi** [comment]
This might related to #305.

**Comment by sharph** [comment]
This may improve when we switch to user requested geolocation.

**Comment by kshepard** [comment]
I suspect this may be closed by #314, but worth double-checking.

**Comment by kshepard** [comment]
Didn't mean to close this yet, reopening until it can be verified.

**Comment by kshepard** [comment]
Verified this is now fixed.
