### ISSUE TITLE
Styling work needed for text input error class

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#280]
`error` class set on input field adds border in need of styling work

**Comment by mtedeschi** [comment]
Can you explain why this was reopened? I added error state styling on the homepage and map page.

**Comment by flibbertigibbet** [comment]
Noted on #302.  Error styling for the homepage needs a way to show up if a field is empty.  Clear a field and hit go, looks like nothing happened.

**Comment by flibbertigibbet** [comment]
Looking at it now on Chromium, I see there's a light red background that gets set, in addition to the text color change.  That wasn't noticeable when we were looking at it in review; may have been the screen, or Safari.
