### ISSUE TITLE
set maxWalkDistance for bike trips

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#281]
The behavior of `maxWalkDistance` has changed in the latest version of OpenTripPlanner.  Now, instead of only affecting total allowed walk distance to transit, it now generally means how far one is willing to travel via any mode to transit.  So, it now effectively works as "max bike distance" for biking/transit trips.

We could add a "max bike distance" dialog now for bike/transit trips (as suggested in #159), or we should at least set `maxWalkDistance` to a high default value for bike/transit trips, to avoid messages saying trip is not possible, when it is possible by biking alone.

**Comment by kshepard** [comment]
The behavior changed from 0.14 to 0.15? If so, what do you think about reverting to 0.14? Seems like that would be the easiest fix.

**Comment by flibbertigibbet** [comment]
The behavior in 0.14 was less desirable. Should only revert if it 0.14 does return bike-only trips for bike/transit requests (I don't think it did).  Bumping `maxWalkDistance` in that case should be simple.
