### ISSUE TITLE
Footer content

### ISSUE THREAD

**Issue by jbranigan** [azavea/cac-tripplanner#292]
Change links to "About" and "How It Works", and point links to Django page.

@nickrogers What would you like the text beneath the links in the footer to be? Right now, they're just design-stage placeholders.

**Comment by sharph** [comment]
@jbranigan Is there an existing page for "How It Works?" What is the slug? ("faq?")

**Comment by nickrogers** [comment]
GoPhillyGo is a project of the Clean Air Council, Azavea, and Warkulwiz Design Associates. The project is funded by the William Penn Foundation.

**Comment by sharph** [comment]
Shall I go ahead and link all of the mentioned organizations?

**Comment by sharph** [comment]
Actually, never mind. There's not a good link style ready to go on that section of the page.

**Comment by jbranigan** [comment]
Thanks, @nickrogers .

@sharph the How It Works page is the faq, yeah. Might make sense to update the slug to how-it-works if it's not too much trouble.
