### ISSUE TITLE
Identical itineraries

### ISSUE THREAD

**Issue by sharph** [azavea/cac-tripplanner#299]
Sometimes identical (or very similar) itineraries are shown

**Comment by sharph** [comment]
Here's a query which seems to bring up the issue:

`http://192.168.8.26/otp/routers/default/plan?fromPlace=39.96432621828807%2C-75.15566825866699&toPlace=39.9819734148758%2C-75.14746851152071&time=02%3A30pm&date=05-15-2015&mode=TRANSIT%2CWALK&arriveBy=false&maxWalkDistance=96560.4&wheelchair=false`

**Comment by kshepard** [comment]
That one looks like a different start and end time.

**Comment by sharph** [comment]
Oh yeah, thanks.

**Comment by sharph** [comment]
Here's one: `https://d2jrlmb413b1yd.cloudfront.net/otp/routers/default/plan?fromPlace=39.942186163991714%2C-75.15189170837402&toPlace=39.94639760290079%2C-75.17523765563965&time=02%3A36pm&date=05-15-2015&mode=TRANSIT%2CBICYCLE&arriveBy=false&optimize=TRIANGLE&triangleSafetyFactor=0.34&triangleSlopeFactor=0.33&triangleTimeFactor=0.33`

**Comment by kshepard** [comment]
Yep, those sure appear to be the exact same.

**Comment by flibbertigibbet** [comment]
Duplicate of #256

**Comment by sharph** [comment]
Indeed.
