### ISSUE TITLE
ESRI geocoder magicKey problem

### ISSUE THREAD

**Issue by kshepard** [azavea/cac-tripplanner#307]
There seems to be a problem with ESRI's magicKey property not actually being respected. I noticed this issue when turning my browser's geolocation off. I searched for 'City Hall', and the suggestions were as expected. Then I click on the 'City Hall' result and it geocodes to a completely different City Hall: 'Pearlridge City Hall', which is located in Hawaii.

@CloudNiner: I believe you added this functionality originally. Have you ever seen this before?

The following are the details of the two queries and their responses:

Suggest query:

`https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/suggest?text=City%20Hall&searchExtent=-76.209582%2C39.467695%2C-74.243725%2C40.725449&category=Address%2CPostal%2CCoordinate+System%2CPopulated+Place%2CPOI&f=pjson`

Suggest response:

`{
 "suggestions": [
  {
   "text": "City Hall",
   "magicKey": "GST7YMc0AM9UOsE9HhFtS5KUUDxMQBNKU1cOnskIBBdOUBotGSyJAnyUns8t7hc0YQWMYcyGnicLZcwuab9QDNFF",
   "isCollection": true
  },
  {
   "text": "City Hall Coffee House, 1 S Broad St, Philadelphia, Pennsylvania",
   "magicKey": "GST7YMc0AM9UOsE9HhFtGTyVGST7YMc0AM9UOsE9DbTVHgA9HhB0Zcp0OhNtGMytaikZQDkKUsNHMoc4Hhp0OSTaSsEqAYwuGPTq7iAm7Py_CR4PIic2CZc0YiD7DsKaCZyAOh5-Dn47Z5E41hpOCPtvDbaF",
   "isCollection": false
  },
  {
   "text": "City Hall, Philadelphia, Pennsylvania, USA",
   "magicKey": "GST7YMc0AM9UOsE3GY8tIS9GOghnYnwZIip_GQypG1cpOh9bZgKZQ1c3YSyaagDIZhkZISWGSo46HgAQ",
   "isCollection": false
  },
  {
   "text": "Old City Hall, 502 Chestnut St, Philadelphia, Pennsylvania",
   "magicKey": "GST7YMc0AM9UOsE9HhFtGTyVGST7YMc0AM9UOsE9DbTVHgA9HhB0Zcp0OhNtGMytaikZQskAUBwAU5xtIS9GOghnYnwZGPT-CZc0YiD7DsKGCZyAOh5-Dn47Z5E41hpOCPtvDbaF",
   "isCollection": false
  },
  {
   "text": "Rockledge City Hall, 121 Huntingdon Pike, Jenkintown, Pennsylvania",
   "magicKey": "GST7YMc0AM9UOsE9HhFtGTyVGST7YMc0AM9UOsE9DbTVHgA9HhB0Zcp0OhNtGMytaikZQskAUBwHUBNtIS9GOghnYnwZGPT-CZc0YiD7DsK7CZyAOh5-Dn47Z5E41hpOCPtvDbaF",
   "isCollection": false
  }
 ]
}`

After the "City Hall" suggestion is selected, the geocode request is sent:

`https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/find?category=Address%2CPostal%2CCoordinate+System%2CPopulated+Place%2CPOI&outFields=StAddr%2CCity%2CRegion%2CPostal&f=pjson&maxLocations=1&text=City+Hall&magicKey=GST7YMc0AM9UOsE9HhFtS5KUUDxMQBNKU1cOnskIBBdOUBotGSyJAnyUns8t7hc0YQWMYcyGnicLZcwuab9QDNFF`

The geocode response is:

`{
 "spatialReference": {
  "wkid": 4326,
  "latestWkid": 4326
 },
 "locations": [
  {
   "name": "Pearlridge City Hall",
   "extent": {
    "xmin": -157.945818,
    "ymin": 21.380936999999999,
    "xmax": -157.93581800000001,
    "ymax": 21.390937000000001
   },
   "feature": {
    "geometry": {
     "x": -157.94081656999975,
     "y": 21.385937132000436
    },
    "attributes": {
     "StAddr": "98-1005 Moanalua Rd",
     "City": "Aiea",
     "Region": "Hawaii",
     "Postal": ""
    }
   }
  }
 ]
}`

**Comment by CloudNiner** [comment]
Oh boy, more fun.

I seem to remember removing the spatial extent parameters from find if a magicKey is provided because there were some inconsistencies when other get params where provided. 

So, I tried making the request with only the params 'f, text, magicKey' and got "Whitemarsh City Hall". So I'm not sure what's going on.

All the docs say is this:
`After you make a suggest request, the typical workflow is to pass the text and magicKey values in a find request, which retrieves the result in less time than passing in a text value by itself.` But as per my attempt above, that doesn't seem to work?

**Comment by CloudNiner** [comment]
Update: Have to pass the text/magicKey combo returned from the suggest service, not the text that is input into the text service:
https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/find?text=City Hall Coffee House, 1 S Broad St, Philadelphia, Pennsylvania&magicKey=GST7YMc0AM9UOsE9HhFtS5KUUDxMQBNKU1cOnskIBBdOUBotGSyJAnyUns8t7hc0YQWMYcyGnicLZcwuab9QDNFF &outFields=StAddr%2CCity%2CRegion%2CPostal&f=pjson

**Comment by kshepard** [comment]
The first suggest result is for "City Hall", not the coffee house.

**Comment by CloudNiner** [comment]
Ugh, ok. Disregard that update comment then. Do we know that the generic "City Hall" refers to Philly city hall? I'm not sure we do. Passing only text, f, magicKey params:
`https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/find?outFields=StAddr%2CCity%2CRegion%2CPostal&f=pjson&maxLocations=1&text=City+Hall&magicKey=GST7YMc0AM9UOsE9HhFtS5KUUDxMQBNKU1cOnskIBBdOUBotGSyJAnyUns8t7hc0YQWMYcyGnicLZcwuab9QDNFF`

Returns:
```
{
 "spatialReference": {
  "wkid": 4326,
  "latestWkid": 4326
 },
 "locations": [
  {
   "name": "Whitemarsh Township Hall",
   "extent": {
    "xmin": -75.257579000000007,
    "ymin": 40.081758999999998,
    "xmax": -75.247579000000002,
    "ymax": 40.091759000000003
   },
   "feature": {
    "geometry": {
     "x": -75.252578302999666,
     "y": 40.086758786000473
    },
    "attributes": {
     "StAddr": "616 Germantown Pike",
     "City": "Lafayette Hill",
     "Region": "Pennsylvania",
     "Postal": ""
    }
   }
  }
 ]
}
```

Which at least seems a bit more consistent with the bounding/category params specified in the suggest request.

**Comment by CloudNiner** [comment]
I'm still not sure why the names would be inconsistent in the two requests though...

**Comment by kshepard** [comment]
Hm, yeah, that's at least more in the ballpark. You're right, we can't know for sure if the "City Hall" refers to the Philly city hall. I'd say it's more likely that it does -- compared to the Whitemarsh Township Hall, but who knows. This magicKey behavior is very strange.

@lliss - I remember you recently did some work related to the magicKey property. Have you run into any issues like this?

**Comment by CloudNiner** [comment]
I just had a thought. I bet the issue is that the first "city hall" result has isCollection: true, which means it represents a grouping of locations and therefore likely can't be mapped to a specific location via find.

I bet if we filter out any suggestion with `isCollection: true` we'll see this go away.

**Comment by kshepard** [comment]
Oh, interesting, good eye. I'll give that a try and see what happens.

**Comment by kshepard** [comment]
Seems to work great. And there was already another suggestion for "City Hall, Philadelphia, Pennsylvania, USA" in the list, so that's the one that would be selected in this specific scenario. Thanks for figuring it out!
