### ISSUE TITLE
Image scaling - mobile

### ISSUE THREAD

**Issue by jbranigan** [azavea/cac-tripplanner#316]
The homepage thumbnail images for the featured articles seem to be getting strangely squashed. Also, the header image on those article pages are just getting pushed to the right / cut off. Maybe they should scale down vertically a bit and stay centered?

**Comment by mtedeschi** [comment]
I had the hero (top) images cover the space, but I went through and have them position absolutely centered now too to show more of the content. I also set the article featured image thumbnails to be fixed to the bottom of the block, so that colored background shows up now.
