### ISSUE TITLE
Mobile mapping - hide elements

### ISSUE THREAD

**Issue by jbranigan** [azavea/cac-tripplanner#317]
Clean up the in-app page to only be showing the featured location details. Basically, hide the location search, direction options, and everything map. We'll be kicking people out to native apps for actual directions.

Some things might still need cleanup after this.

**Comment by mtedeschi** [comment]
@jbranigan I just want to clarify: we should hide any ability to get to the directions search (hide the tab entirely), hide the explore location search bar. We should keep the "get directions" buttons for the featured locations, but we'll wire those up in the future to take you out to native apps later (so they'll never get to our directions search).

**Comment by jbranigan** [comment]
You've got it exactly @mtedeschi
