### ISSUE TITLE
Typeahead styling

### ISSUE THREAD

**Issue by kshepard** [azavea/cac-tripplanner#319]
Manual geolocation was just added in #314. This includes an icon (currently a globe) that can be pressed to fetch the user's current location. It's only displayed when the input field is empty. This icon can use some basic styling enhancements, as well as possibly changing the image to a target. In addition, the typeahead has an 'x' icon the pops up on hover and allows clearing the input -- this can probably also use some minor styling tweaks.

**Comment by mtedeschi** [comment]
I noticed this and pushed a small styling fix for this in #318, but it could use some more work. I'll look into it.

**Comment by flibbertigibbet** [comment]
As noted on #338, discover tab typeahead styling still needs tweaking.
