### ISSUE TITLE
share your ride, link to turn by turn directions 

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#320]
![image](https://cloud.githubusercontent.com/assets/12200440/7727416/99790cca-fed6-11e4-9fd9-054372628a0b.png)
Black bar through the GoPhillyGo logo

**Comment by jbranigan** [comment]
Duplicate of https://github.com/azavea/cac-tripplanner/issues/311, merged and fixed yesterday. We'll push this change and others today.
