### ISSUE TITLE
Doesn't take me to the closest station

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#321]
![image](https://cloud.githubusercontent.com/assets/12200440/7728732/f1cc82d2-fede-11e4-8546-133322b32c1e.png)
From 13th and Locust, this directed me to 15th and Locust, while there is a station at 13th and Locust

**Comment by flibbertigibbet** [comment]
Looks like the planner may have decided not to cross the street at that point; an origin of 1301 Locust routes to the 13th St station.
