### ISSUE TITLE
directions start at city hall even though the person put their home address in

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#336]
![image](https://cloud.githubusercontent.com/assets/12200440/7776656/7cd27db2-008a-11e5-8759-922be99c6b2f.png)
"I also put in my home address but it gave me directions from city hall. It still shows the origin as my home address on the left but the map shows the origin as city hall. It seems to do this every time I ask for directions. I attached a screen shot. "

**Comment by jbranigan** [comment]
Hard to tell what browser is being used there. It looks like the address didn't get completed, and so isn't being set. I set the same address and it worked. Do you know which browser and OS version is being used?

**Comment by nickrogers** [comment]
"I'm on chrome. It actually only happens when I put in the street address without Philadelphia, PA in it…."

**Comment by nickrogers** [comment]
instead of starting at city hall, is there a way for it to prompt you to complete the address?

**Comment by jbranigan** [comment]
Weird. What steps to do you take to get it to not autocomplete?

**Comment by jbranigan** [comment]
If I click the search button, it doesn't do anything and outlines the address box in red.
![screen shot 2015-05-22 at 2 44 58 pm](https://cloud.githubusercontent.com/assets/1508618/7777460/350cf258-0091-11e5-8e6a-0e2134a451b5.png)

**Comment by nickrogers** [comment]
I just replicated it here. If you type "3603 Baring Street" + TAB + a complete address in the "to" box it gives me directions from city hall

**Comment by nickrogers** [comment]
![image](https://cloud.githubusercontent.com/assets/12200440/7777477/607096d4-0091-11e5-9e47-c12651ac10a5.png)
