### ISSUE TITLE
Last searched travel shed showing up when clicking on destination

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#340]
From the home page I clicked on Palmyra Cove, and the screen it took me to had a 30 minute travel shed from the Holmesburg Junction Septa Station, which I believe was the last place I had searched. I think a travel shed form the destination might be appropriate - to show the area around that destination that is X minutes away. Kind of a reverse travel shed.

![image](https://cloud.githubusercontent.com/assets/12200440/7821080/5fa3e0ae-03ba-11e5-9462-8d70d263a130.png)

**Comment by flibbertigibbet** [comment]
@jbranigan revert?

**Comment by jbranigan** [comment]
We should keep the travelshed on the user's origin. I get the idea of the reverse travelshed, but think this would be confusing for most users, as well as open up room for potential bugs.

**Comment by jbranigan** [comment]
Good example of weird functionality is clicking TULPEHAKING NATURE CENTER AT ABBOTT MARSHLAND on the home page. The result should be a map centered on this location, rather than on the origin/travel shed.

**Comment by flibbertigibbet** [comment]
so... revert?

**Comment by jbranigan** [comment]
Nope, just center the map on the featured location - similar to if you clicked it in the sidebar, and the map pans.

**Comment by jbranigan** [comment]
Also, highlight the location with the lighter green color, as if it were clicked on in the sidebar.
