### ISSUE TITLE
Directions to Palmyra Cove show that Tacony-Palmyra bridge walkway is not available for directions

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#341]
Directions are making me avoid a short trip across the Tacony Palmyra Bridge walkway, which is also preventing a travel shed from the part of Philadelphia showing Palmyra Cove as nearby.

Bike + Transit 
![image](https://cloud.githubusercontent.com/assets/12200440/7821196/18cfe60e-03bb-11e5-9c5d-3488fa2c12e4.png)

Bike only
![image](https://cloud.githubusercontent.com/assets/12200440/7821168/e212a764-03ba-11e5-850d-26b5801fbc99.png)

Walk only
![image](https://cloud.githubusercontent.com/assets/12200440/7821178/f25981a6-03ba-11e5-9b20-c1c8acdddaa0.png)

Transit + walk (unavailable)
![image](https://cloud.githubusercontent.com/assets/12200440/7821189/062e1f20-03bb-11e5-817c-c8d45bb334ec.png)

**Comment by flibbertigibbet** [comment]
There's likely an issue with OpenStreetMap data not properly labeling the bridge walkway or its pedestrian access points.

**Comment by flibbertigibbet** [comment]
Although the bridge itself was labeled in OpenStreetMap as having a sidewalk, there were no bike/pedestrian access links to the bridge sidewalk on either side.  I've edited OpenStreetMap to add them.

**Comment by flibbertigibbet** [comment]
![image](https://cloud.githubusercontent.com/assets/960264/7864255/015396d6-052f-11e5-9e9b-b48938c898f1.png)

Bike/ped directions across Palmyra work with updated OSM data.
