### ISSUE TITLE
directions starting in a weird place

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#348]
typed in "135 south 19th street, philadelphia, pa" and had directions show me somewhere in the Northeast. I didn't type in the zipcode, but if the site isn't sure then maybe it should prompt me for a zipcode? I would think City and State would be good enough though.
![image](https://cloud.githubusercontent.com/assets/12200440/7867436/185d2148-0544-11e5-91a4-765a4ecdb6f0.png)

**Comment by nickrogers** [comment]
Actually, I'm just realizing that it put me in my most recent search, the Holmesburg Junction Station.

Of note, I also didn't type in the zipcode for my ending address, but it got that right.

**Comment by jbranigan** [comment]
Same problem as https://github.com/azavea/cac-tripplanner/issues/336
