### ISSUE TITLE
Not able to move the map once directions selected

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#349]
I just tested this and was able to move the map on my browser, chrome. But see comment below from Erik at SEPTA:

"This is very cool, Nick, very sleek interface. I particularly like the integration with the BikeShare locations and real-time docking info.

One technical problem I’m having is after selecting a set of parameters in the “Get Directions” field, I’m not able to click on the map and move it. Could be an issue with my browser, Safari. Not sure how I can “print screen” this problem per your instructions below since it’s not a static issue, but I thought I’d send it your way anyway.

I’ll let you know if I see any other issues.

Erik"

**Comment by nickrogers** [comment]
"Having the same issue on iPad (Safari) and IE. Firefox seems to be working well."

**Comment by jbranigan** [comment]
Confirmed this bug in desktop Safari.

**Comment by flibbertigibbet** [comment]
Observable on current beta server, but does not happen when run locally.  Possible minification issue?
