### ISSUE TITLE
Add Google Tag Manager snippet

### ISSUE THREAD

**Issue by jbranigan** [azavea/cac-tripplanner#353]
From the docs: "Paste this snippet into your website template page so that it appears immediately after the opening <body> tag". The below snippet should be good to go.

```
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-KNZ9R2"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KNZ9R2');</script>
<!-- End Google Tag Manager -->
```

**Comment by flibbertigibbet** [comment]
Snippet fails to load in production.  Get a 404 Not Found on http://www.googletagmanager.com/gtm.js?id=GTM-KNZ9R2 .

**Comment by flibbertigibbet** [comment]
Apparently the tag manager will return a 404 until the [container is published](https://support.google.com/tagmanager/answer/6107163?hl=en).

**Comment by jbranigan** [comment]
Looks like the container is now published
