### ISSUE TITLE
Directions go to wrong place

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#358]
![image](https://cloud.githubusercontent.com/assets/12200440/7969200/392f6d90-0a03-11e5-9f6b-1e31bd558abe.png)
I copied and pasted an exact address (TInicum Township Town Hall, 629 North Governor Printz Blvd, Essington, PA 19029) and it took me to another place - I think that might be a recently searched address but I'm not sure. I deleted "Tinicum Township Town Hall" and just the address gets closer but not 100% (in this second screen shot the actual address is located at roughly Jansen and Industrial Highway).
![image](https://cloud.githubusercontent.com/assets/12200440/7969267/b7cc86ce-0a03-11e5-9c18-c8fe6c668c9e.png)

So seems like two issues: the first is that the software didn't recognize the address I searched with the label "tinicium town hall" so it just reverted to a recently searched address. If it's not sure for some reason it should ask me to try again instead of taking me to an altogether different place. The second issue is that once I adjusted my search, it was closer but still wrong about where that address is located.

**Comment by flibbertigibbet** [comment]
Currently only addresses accepted from the autosuggest get used.

@CloudNiner: know how to deal with user input differing from typeahead trigger event input?

**Comment by CloudNiner** [comment]
Hmmm, yeah, I _think_ you'd have to do something like see if a typeahead result is populated when the user clicks the submit button, and if not just do a direct Geocoder.search() on the text in the input field.

**Comment by kshepard** [comment]
Just submitted a PR (#362), that addresses part of this issue -- it fixes the problem where the last searched address is reverted to when searching. As for the address of "629 North Governor Printz Blvd, Essington, PA 19029" -- I'm getting the same location when I query the ESRI geocoder, so for some reason that's where it erroneously thinks this address is located.
