### ISSUE TITLE
html language showing up in directions, and time suggestion

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#360]
![image](https://cloud.githubusercontent.com/assets/12200440/7969640/48467050-0a06-11e5-87cb-12b70dd913d9.png)

Also, we have a start and end time of day, but not for the bus pickup. Consider putting a time down for any public transportation pickups/dropoffs in the trip?

**Comment by jbranigan** [comment]
Also add lengths of individual turns, in distance.
