### ISSUE TITLE
Website thinks Rittenhouse Sq is bike path, directs users to bike on sidewalk

### ISSUE THREAD

**Issue by CorynWolk** [azavea/cac-tripplanner#361]
I searched directions to 17th and Spring Garden from our office by bicycle. The website instructed me to bike east on Walnut from 19th to 18th. Since Walnut runs west, it instructed me to bike on the "path" on Rittenhouse Square, but the "path" is just the Rittenhouse sidewalks, which are forbidden to bikes. Nick said that he had this happen to him but forgot to screenshot it and then couldn't replicate it. (I was just able to now, though.)
![rittenhouse square bike path issue](https://cloud.githubusercontent.com/assets/12202740/7969884/0f0ac028-0a08-11e5-8d4e-340d4d01efc8.jpg)

**Comment by flibbertigibbet** [comment]
Directions steps with the walking figure to the left instead of the bike indicate you are to walk your bike for that segment.  The trip planner reads the tags from OpenStreetMap that indicate whether biking is allowed on a segment; fixing incorrect permissions tags may be done by [editing OpenStreetMap](http://wiki.openstreetmap.org/wiki/Editing).

**Comment by CorynWolk** [comment]
That makes sense. In this instance, though, when I click the "Turn left onto path" under the bike part of the directions, it highlights the area highlighted in the screenshot--the start of the path--indicating that you start biking while still on the sidewalk on Walnut Street. Nick pointed out that if you're walking your bike at that point, there's no reason to cross the street to walk on the sidewalk on the other side of the street and then cross back at 18th to get on your bike. We were also wondering if there's a way to eliminate some of the micro turns in the directions (such as turning twice to get to and cross the crosswalk at 19th and Walnut) to make the directions easier to understand.
