### ISSUE TITLE
Safari input styling

### ISSUE THREAD

**Issue by jbranigan** [azavea/cac-tripplanner#366]
Strange looking inputs. Same on the home page. Safari on OS X.

![screen shot 2015-06-05 at 4 40 33 pm](https://cloud.githubusercontent.com/assets/1508618/8014813/c8b49806-0ba1-11e5-8cef-1074162ad275.png)

**Comment by sharph** [comment]
Some more screenshots of this problem
![safari9](https://cloud.githubusercontent.com/assets/539905/8042093/bddf937c-0dea-11e5-978d-350623144106.png)
![safari9-2](https://cloud.githubusercontent.com/assets/539905/8042095/c0ae7bf4-0dea-11e5-8842-639a3b7291f4.png)
