### ISSUE TITLE
Starting from City Hall instead of address that is in there (another tester giving this feedback)

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#367]
![image](https://cloud.githubusercontent.com/assets/12200440/8037175/56517222-0dca-11e5-8a6d-dc30ff9a3c28.png)

**Comment by nickrogers** [comment]
This was an email I had missed from May 28th, would this have changed since then? I just tried it and it worked for me.

**Comment by kshepard** [comment]
Yes, I just tried it out and it worked for me too. A fix for this problem was deployed on Friday the 5th, so this should no longer occur.

**Comment by nickrogers** [comment]
thanks!

**Comment by kshepard** [comment]
No problem! I'll close this issue.
