### ISSUE TITLE
Address not working

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#368]
I copied and pasted 401 Main Street, Riverton, NJ  08077 into the address box and it didn't work. When I started typing the address I was able to select it from the drop down and it worked fine. I like that instead of taking me somewhere incorrect, it makes me re-enter until something works but 1) Just turning red might not be clear enough for everyone to understand, maybe something pops up requesting you to re-enter the address starting by typing it all out? 2) Why would this not work if I am copy/pasting an exact address with city, state, zip and everything typed out?

![image](https://cloud.githubusercontent.com/assets/12200440/8037807/f2f1e7a8-0dcd-11e5-947e-51219a157336.png)

**Comment by jbranigan** [comment]
@nickrogers It looks like the spelling was slightly different from what the geocoding service wants. I pasted your address in, and there was an option to select from the list - I picked it and it worked. There's a lot of logic in play behind the scenes here and we can't accept free text that doesn't match a list option. 

I'll see if there's something we can do to be more explicit with the error feedback.

**Comment by nickrogers** [comment]
@jbranigan  What is the spelling difference the geocoder wanted? I didn't notice a difference. 

Should we advise to not type out an address or copy/paste, but wait until an option drops down and select that as the best way to use the directions?

**Comment by jbranigan** [comment]
It wanted "St" instead of "Street". Usually the list option works intuitively - this is an edge case that is difficult to work around. Typing and copy/paste should usually work well - selecting from the list is the only way the software will be able to provide directions.

**Comment by jbranigan** [comment]
Modal alert would work here: "We had trouble recognizing that address. Please try again and select an option from the list. Intersections are difficult to interpret - try using an address instead."

**Comment by jbranigan** [comment]
This does not seem to be working

**Comment by jbranigan** [comment]
Ah, I see - it's for destination only, not origin. Can we get both?

**Comment by flibbertigibbet** [comment]
It is for both.  Because there is a default origin but not a default destination, it will fall back to the default origin address.
