### ISSUE TITLE
Numeric up-down buttons on FF38, Windows 8 doesn't display correctly

### ISSUE THREAD

**Issue by sharph** [azavea/cac-tripplanner#369]
![ff38-win](https://cloud.githubusercontent.com/assets/539905/8042003/254ffbba-0dea-11e5-83b1-a7a9698ad7d6.png)

via browserstack's browser

**Comment by mtedeschi** [comment]
Tested in FF38 on Windows 8.1 and didn't run into the issue. Closing for now.
