### ISSUE TITLE
Address doesn't disappear when X is clicked

### ISSUE THREAD

**Issue by sharph** [azavea/cac-tripplanner#371]
![ie10](https://cloud.githubusercontent.com/assets/539905/8042078/a0a5f1f2-0dea-11e5-8787-513c1409f854.png)

IE10

**Comment by mtedeschi** [comment]
Not sure if this is meant to be assigned to me @jbranigan—is this because of styling problems?

**Comment by flibbertigibbet** [comment]
Tested on IE 11, and the input clear buttons work fine now on all the address fields.

However, the address field on the "Discover Places" tab has a giant clear 'X' (they're normal-sized elsewhere.)
