### ISSUE TITLE
Indego official map pin

### ISSUE THREAD

**Issue by jbranigan** [azavea/cac-tripplanner#373]
Also, change the text of the legend to say “Indego Bike Share Stations”. File on the file share

**Comment by jbranigan** [comment]
projects/CleanAirCouncil_TripPlanner/downloads/Indego Map Marker.ai

**Comment by CloudNiner** [comment]
For this icon, we'll need a png and an @2x png of the same size as the icons here:
https://github.com/lvoogdt/Leaflet.awesome-markers/blob/2.0/develop/dist/images/markers-plain.png 

We can reuse the shadow icon from that same project, so we don't need a shadow.

**Comment by ctaylo37** [comment]
OK,  both files are in:
smb://FILESHARE.internal.azavea.com/projects/CleanAirCouncil_TripPlanner/downloads
