### ISSUE TITLE
Updated Image for homepage header

### ISSUE THREAD

**Issue by WarkulwizDesign** [azavea/cac-tripplanner#376]
We have created new map art using a higher resolution image that will also be used on the GoPhillyGo print piece. 
Link to download: https://www.dropbox.com/s/pxp0fihthszqdbq/150610_Philadelphia-Map-Cover.png?dl=0
This will replace the current image of the cyclists on the path. Any questions let me know!

**Comment by jbranigan** [comment]
@WarkulwizDesign Is this image something we can use without a license? It looks like a Google Maps base map. Just want to make sure.

**Comment by WarkulwizDesign** [comment]
This is liscensed art that has been purchased for the print piece, but the
coloring has obviously taken hints from Google Maps. It is a vector map we
used to print materials created for GPG. I have edited it to match what GPG
is using on the live site, with the exception of the parks and water
sources which have color added to them. I will update the header file
shortly.

On Wed, Jun 24, 2015 at 11:12 AM, jbranigan <notifications@github.com>
wrote:

> @WarkulwizDesign <https://github.com/WarkulwizDesign> Is this image
> something we can use without a license? It looks like a Google Maps base
> map. Just want to make sure.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/cac-tripplanner/issues/376#issuecomment-114902416>
> .
>



-- 
*Emily Zuwiala*
Graphic Designer
Warkulwiz Design Associates
89 E Wynnewood Road
Merion Station, PA 19066
215.988.1777
www.warkulwiz.com

**Comment by WarkulwizDesign** [comment]
Here is an new header approved by CAC. The coloring has been edited to match the GPG map, with some green/blue for park/water. The color overlay has been darkened so all white type reads and even the black beta reads. Below is the png and the layered Ai. file. I'm not sure if you upload the flat image or the background and overlay so just in case the blue overlay is hex 66b5eb at 60% opacity. The map file is currently masked to fit the 2800x800 px ratio but the art is very large and can be extended if needed.

Dropbox file for ai: https://www.dropbox.com/s/vk7k6492n787lee/150624-GPG-Map-Cover.ai?dl=0
![150624-gpg-map-cover](https://cloud.githubusercontent.com/assets/12275457/8339264/29a5d06c-1a84-11e5-9df0-81376742ad54.png)
