### ISSUE TITLE
Feature location images no longer accessible in development

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#387]

**Comment by jbranigan** [comment]
What does this mean?

**Comment by flibbertigibbet** [comment]
In local vagrant development environment after reprovisioning database and app servers, all the featured location image links are broken.   Production seems fine (it's using AWS to store and retrieve images.)

![image](https://cloud.githubusercontent.com/assets/960264/8212385/5e9baddc-14e9-11e5-95dd-2f8ddb5269fe.png)

**Comment by flibbertigibbet** [comment]
Destroyed and reprovisioned both again, and images are back.  There may be something strange going on with our migrations, that after reprovisioning without destroying, the featured locations were in place, but not their images.
