### ISSUE TITLE
GPG logo is cut off in directions link in mobile view

### ISSUE THREAD

**Issue by WarkulwizDesign** [azavea/cac-tripplanner#390]
GPG Logo is cut off from the map image in a mobile view. This link was accessed from an email on an iPhone 5. 

![150616-gpg-mobile-directions-link-error](https://cloud.githubusercontent.com/assets/12275457/8186468/75b06700-1418-11e5-957d-40d098b1baa5.png)

**Comment by flibbertigibbet** [comment]
Duplicate of #229
