### ISSUE TITLE
Will there be an online form?

### ISSUE THREAD

**Issue by WarkulwizDesign** [azavea/cac-tripplanner#395]
Will an online form be added to the site? I know originally we talked about it going through the About section, but since there is a submenu in the footer with About and How it Works - I think we could add a 'Subscribe' section. CAC wants to continue to create a userbase of interested parties for email marketing.
![screen shot 2015-06-22 at 11 19 48 am](https://cloud.githubusercontent.com/assets/12275457/8285402/15d5a62a-18d1-11e5-8105-7fd185c55f7c.png)

**Comment by jbranigan** [comment]
Can you provide documentation for where the form should send data? A code snippet would be even better.

**Comment by WarkulwizDesign** [comment]
Hi John,

For the interim site we used Jotform to create our form - do you want to
proceed with using the same form for that?

The form includes:
First Name
Last Name
Email Address
Checkbox to receive emails from GoPhillyGo

Let me know how you want to proceed.
Thanks,
Emily

On Mon, Jun 22, 2015 at 2:36 PM, jbranigan <notifications@github.com> wrote:

> Can you provide documentation for where the form should send data? A code
> snippet would be even better.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/cac-tripplanner/issues/395#issuecomment-114210816>
> .
>



-- 
*Emily Zuwiala*
Graphic Designer
Warkulwiz Design Associates
89 E Wynnewood Road
Merion Station, PA 19066
215.988.1777
www.warkulwiz.com

**Comment by jbranigan** [comment]
Can you ask your developer to provide the code for this form? Server locations, API keys, validation, etc is already figured out and coded. I'm not sure we'll just be able to drop it in, but it'd be great if we could.

**Comment by jbranigan** [comment]
@flibbertigibbet Do you think this would work if we drop it in?

```
<script src="http://d2g9qbzl5h49rh.cloudfront.net/static/prototype.forms.js" type="text/javascript"></script>
<script src="http://d2g9qbzl5h49rh.cloudfront.net/static/jotform.forms.js?3.2.6775" type="text/javascript"></script>
<script type="text/javascript">
   JotForm.init(function(){
	  JotForm.onSubmissionError="jumpToSubmit";
   });
</script>
<form class="jotform-form" action="http://submit.jotform.us/submit/51094584186159/" method="post" target="_blank" name="form_51094584186159" id="51094584186159" accept-charset="utf-8">
	<input type="hidden" name="formID" value="51094584186159" />
	<div class="row">
		<div class="col-xs-12 col-sm-6">
			<input type="text" name="q1_firstName" placeholder="First Name" value="">
		</div>
		<div class="col-xs-12 col-sm-6">
			<input type="text" name="q3_lastName" placeholder="Last Name" value="">
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<input type="text" name="q4_emailAddress" placeholder="Email Address" value="">
		</div>
	</div>
	<div class="submit row">
		<div class="col-xs-12">
			<label><input type="checkbox" name="agree"> I agree to receive emails from GoPhillyGo</label><br class="visible-xs">
			<input type="submit" value="SUBMIT">
		</div>
	</div>
	<input type="hidden" id="simple_spc" name="simple_spc" value="51094584186159" />
	<script type="text/javascript">
		document.getElementById("si" + "mple" + "_spc").value = "51094584186159-51094584186159";
	</script>
</form>
```

**Comment by WarkulwizDesign** [comment]
I'm just confirming that if I share the current code for the form it
doesn't mess up the code for the interim site. If we are good to go, I can
share the embedded code Jotform provides.

On Tue, Jun 23, 2015 at 2:03 PM, jbranigan <notifications@github.com> wrote:

> Can you ask your developer to provide the code for this form? Server
> locations, API keys, validation, etc is already figured out and coded. I'm
> not sure we'll just be able to drop it in, but it'd be great if we could.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/cac-tripplanner/issues/395#issuecomment-114592181>
> .
>



-- 
*Emily Zuwiala*
Graphic Designer
Warkulwiz Design Associates
89 E Wynnewood Road
Merion Station, PA 19066
215.988.1777
www.warkulwiz.com

**Comment by WarkulwizDesign** [comment]
Here is the code from JotForm:
<script type="text/javascript" src="
http://form.jotform.us/jsform/51094584186159"></script>

It is important to CAC that a form is on the site. CAC wants to continue to
grow its transportation user base for future marketing of GPG and other
sustainable transportation programs. Let me know how it works out!


On Tue, Jun 23, 2015 at 2:37 PM, Emily Zuwiala <emily@warkulwiz.com> wrote:

> I'm just confirming that if I share the current code for the form it
> doesn't mess up the code for the interim site. If we are good to go, I can
> share the embedded code Jotform provides.
>
> On Tue, Jun 23, 2015 at 2:03 PM, jbranigan <notifications@github.com>
> wrote:
>
>> Can you ask your developer to provide the code for this form? Server
>> locations, API keys, validation, etc is already figured out and coded. I'm
>> not sure we'll just be able to drop it in, but it'd be great if we could.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/azavea/cac-tripplanner/issues/395#issuecomment-114592181>
>> .
>>
>
>
>
> --
> *Emily Zuwiala*
> Graphic Designer
> Warkulwiz Design Associates
> 89 E Wynnewood Road
> Merion Station, PA 19066
> 215.988.1777
> www.warkulwiz.com
>



-- 
*Emily Zuwiala*
Graphic Designer
Warkulwiz Design Associates
89 E Wynnewood Road
Merion Station, PA 19066
215.988.1777
www.warkulwiz.com
