### ISSUE TITLE
Indego info window formatting

### ISSUE THREAD

**Issue by jbranigan** [azavea/cac-tripplanner#396]
Text looks odd.

![screen shot 2015-06-23 at 2 32 02 pm](https://cloud.githubusercontent.com/assets/1508618/8314033/c7c23afe-19b4-11e5-9a64-c91985236478.png)

**Comment by mtedeschi** [comment]
Tested in Safari, Firefox, Chrome—don't see this issue. Which browser are you running into it with?

**Comment by flibbertigibbet** [comment]
See staging server (has latest styling changes merged in).
