### ISSUE TITLE
GPG logo with BETA signature

### ISSUE THREAD

**Issue by WarkulwizDesign** [azavea/cac-tripplanner#400]
Here is a mock up for the GPG Beta for the site. 'BETA' is set in Cabin Bold at 21 pt. Below is a flat and a Dropbox link to an Ai file. Let me know if you need anything else!
File link: https://www.dropbox.com/s/pmqua7yjfg7srit/150624-GPG-Beta-Logo.ai?dl=0
![150624-gpg-beta-logo-01](https://cloud.githubusercontent.com/assets/12275457/8330895/b2c16dc0-1a52-11e5-9bc5-a71b51b9226f.png)

**Comment by jbranigan** [comment]
What are your thoughts about when the logo is shown against a white background?

**Comment by WarkulwizDesign** [comment]
GPG does have brand guidelines, so it depends what it is being used for. There is the main logo, with or without the tagline, and then there is a flexible branding system. The flexible system has other logo options that may tailor to the subject better - i.e. transit use can use the logo with the bus wheels whereas a cycling event can use the bicycle wheel logo. What use will you need the logo for or is this strictly for the cover on the website?
![150312-gophillygo-logo-options](https://cloud.githubusercontent.com/assets/12275457/8331735/d428729c-1a57-11e5-9e44-75e557600691.jpg)

**Comment by jbranigan** [comment]
I guess I'm more asking about the white font of the Beta tag for the map page and the share directions page.

**Comment by WarkulwizDesign** [comment]
I am playing around with it a little bit more and I think it may work better in black and reduced in size to 15. This way it will be an easy transition to the map page. 
![screen shot 2015-06-24 at 11 03 28 am](https://cloud.githubusercontent.com/assets/12275457/8333406/b3d93702-1a60-11e5-9d84-ab50ff84f2da.png)

Also - the does the current cover art look too busy? I am worried that the map texture in the back needs the opacity to be taken back a bit so the black street names are not competing with the headline. Also while this is the print piece GPG map, without the Indego stations iti may look too much like Google Maps. Let me play with the coloring to see if I can alter it to look closer to the GPG map with some color added.
