### ISSUE TITLE
Directions to Camden Children's Garden lead to DE (and are disjointed)

### ISSUE THREAD

**Issue by CorynWolk** [azavea/cac-tripplanner#404]
I tried making a route from West Philly to somewhere in Camden. I started typing Camden, and Camden Children's Garden (one of our featured destinations) came up in the drop-down menu. It didn't have the exact address listed. (I later noticed that Camden Children's Garden with the full address in NJ appears a second time farther down the drop-down menu.)

I selected the Camden Children's Garden without the address. The site gave me a route to Bellefonte, DE, 3 hours away. It looks like that's because the Children's Garden is on Riverside Drive in Camden, and there is a Riverside Drive in Bellefonte, DE. The itinerary is pretty bizarre--at one point, you get off a SEPTA bus in a parking lot, walk a few feet (though that's not shown in the directions/line), take that same route in a loop around the parking lot to another bus stop, and then get on a DART bus.
![de 3 bus bug](https://cloud.githubusercontent.com/assets/12202740/8361918/dcce899e-1b43-11e5-933c-fe05155b3f7a.jpg)

Farther along, you get off a DART bus, presumably walk a couple blocks, then take another bus in the opposite direction, then get onto another bus--except for that 3rd bus's route intersects with the first's, so presumably you could have just gone from bus 1 to bus 3.
![de bus intersect](https://cloud.githubusercontent.com/assets/12202740/8362220/ab0b1f42-1b45-11e5-8ade-87c1f5c695e1.jpg)

At the very end of your trip, you take the bus past the destination, then switch buses to take a bus back past the destination.
![de destination overshoot](https://cloud.githubusercontent.com/assets/12202740/8362115/17722578-1b45-11e5-9e68-e95127a7abb7.jpg)

Obviously, the main issue here is that you should only be offered the choice of directions to a Camden Children's Garden in Camden, and not in DE. But I thought it was worthwhile to flag the weird things going on with the directions themselves as well.

**Comment by jbranigan** [comment]
@CorynWolk @nickrogers

It looks like the Camden Children's Garden location in the app is incorrect - it's showing up in Delaware. This can be fixed through the admin interface.

**Comment by CorynWolk** [comment]
Is that something you'd like us to go in and change?

Also, is the weird bus scheduling/routing issue something that Azavea has control over, or is that a bug in OpenTripPlanner?

**Comment by flibbertigibbet** [comment]
Regarding the routing, it's more likely an issue with Delaware's bus data, and/or the OpenStreetMap tags for the area.

**Comment by jbranigan** [comment]
Yes, fixing the location in the admin interface would be helpful.

**Comment by CorynWolk** [comment]
Fixed it! For some reason it wasn't updating the point on the map in the back-end correctly even though the address was correct, so I moved the point on the map.

**Comment by jbranigan** [comment]
Great, thanks!
