### ISSUE TITLE
Schuylkill Center for Environmental Education labeled weirdly

### ISSUE THREAD

**Issue by CorynWolk** [azavea/cac-tripplanner#405]
This one is pretty minor:

If you start typing Schuylkill Center for Environmental Education, you get two options: Schuylkill Center for Environmental Education with no address (though the directions lead to the right location) or the "Schuylkill Center Environmental Ctr" with the address. The latter is obviously a little off.

**Comment by flibbertigibbet** [comment]
One is the featured location, as pulled from the app database.  The other is coming from the geocoder places.
