### ISSUE TITLE
How should videos be inserted into spotlight posts?

### ISSUE THREAD

**Issue by WarkulwizDesign** [azavea/cac-tripplanner#407]
I realize embedding the videos has not been figured out just yet, but how should a video be added to a spotlight post? It would work best if it could be a popup window - which when I checked off and provided dimensions of 600x900 px, I received the message below. I know the video can open up in a new tab, but I'd like to avoid sending visitors to a new tab when the option for a pop up window does exist.
![screen shot 2015-06-25 at 4 56 20 pm](https://cloud.githubusercontent.com/assets/12275457/8365479/5fd459ce-1b5b-11e5-9f4a-113abe669932.png)

**Comment by jbranigan** [comment]
I think when we tested earlier, we were using youtube embed iframes that play on the page. They include a fullscreen button and worked without the popup.

**Comment by WarkulwizDesign** [comment]
I was able to embed the iframe, but once the page is edited it removes the
embedded code from the source html. So anytime the page is edited -- text
or imagery -- the iframe html is removed. It should be fine for the launch,
but lets take another look at this in the future.

On Fri, Jun 26, 2015 at 2:14 PM, jbranigan <notifications@github.com> wrote:

> I think when we tested earlier, we were using youtube embed iframes that
> play on the page. They include a fullscreen button and worked without the
> popup.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/cac-tripplanner/issues/407#issuecomment-115822180>
> .
>



-- 
*Emily Zuwiala*
Graphic Designer
Warkulwiz Design Associates
89 E Wynnewood Road
Merion Station, PA 19066
215.988.1777
www.warkulwiz.com
