### ISSUE TITLE
Destination directions are routing from City Hall 

### ISSUE THREAD

**Issue by WarkulwizDesign** [azavea/cac-tripplanner#413]
When using the 'Explore Nearby Locations' from the hompenage and selecting one of the GPG destinations when selecting in the "from" area, the map is defaulting to city hall as the starting point. In both instances, 'Bartram's Garden' and 'Tulpehakin Nature Center' were selected from one of the populated items that appears as you type. 
![150629-1](https://cloud.githubusercontent.com/assets/12275457/8413640/f83d1672-1e5f-11e5-8d2f-64e2d4a713a0.png)
![150629-2](https://cloud.githubusercontent.com/assets/12275457/8413642/f8448f42-1e5f-11e5-9472-e639ad1c4bef.png)
![150629-3](https://cloud.githubusercontent.com/assets/12275457/8413639/f83c60f6-1e5f-11e5-9e62-0d8a3eb4e804.png)
![150629-4](https://cloud.githubusercontent.com/assets/12275457/8413641/f83e51e0-1e5f-11e5-9d6c-fbad91e55441.png)

**Comment by flibbertigibbet** [comment]
Partially fixed in #416
