### ISSUE TITLE
Address not working

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#422]
![image](https://cloud.githubusercontent.com/assets/12200440/8422127/4b6dd6ac-1ea5-11e5-9e6a-36a120e3e29a.png)
Not an intersection. This address was selected from the list!

**Comment by nickrogers** [comment]
OK I clicked it again and this time a travel shed did pop up, but it is centered and zoomed in on Bartram's Garden.
![image](https://cloud.githubusercontent.com/assets/12200440/8422140/813b4332-1ea5-11e5-8693-07033ff9466f.png)

**Comment by jbranigan** [comment]
The address is working fine for me. We can take a look at the Bartram's Garden zoom - I have an idea why that might be happening, but it follows a specific set of steps to reproduce.

**Comment by nickrogers** [comment]
Yea just happened again, this time for Palmyra Cove when doing a travel shed for where we will be this morning. The travel shed is correct, the zoom/centering is what is wrong.

![image](https://cloud.githubusercontent.com/assets/12200440/8432131/2714af8a-1f0c-11e5-8f3c-06f37f7ca2f2.png)

**Comment by jbranigan** [comment]
If you could note specific steps to reproduce this, please include them in a comment. I'm not able to reproduce it at the moment.

**Comment by nickrogers** [comment]
Palmyra Cove is the last place I got directions to, and then the next thing i did was explore from a different address. Palmyra Cove also stayed lit up in the highlighted green in that travel shed, and was displayed on the side as you can see.

**Comment by nickrogers** [comment]
And this is doing a travel shed search from the home page

**Comment by flibbertigibbet** [comment]
I can only reproduce this by typing in the new address, then clicking away from the address field without selecting the suggested address.

The user needs to accept a suggested address, either by clicking on it, or hitting the 'enter' key while in the address box.

**Comment by jbranigan** [comment]
Steps to reproduce:
*   Get point-to-point directions to a featured location
*   Go back to home page and switch to "Explore" mode
*   Enter a new origin address, hit go
*   The map is still centered on the featured location
