### ISSUE TITLE
Facebook sharing not working

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#423]
![image](https://cloud.githubusercontent.com/assets/12200440/8422201/772dd9d0-1ea6-11e5-92c2-b78b420ade5d.png)

**Comment by jbranigan** [comment]
@nickrogers The URL in Facebook needs to be updated from beta.gophillygo.org to just gophillygo.org

**Comment by nickrogers** [comment]
Where should this happen? We have changed it where we can find it, and still getting an error

**Comment by jbranigan** [comment]
This looks like one solution: https://www.facebook.com/help/community/question/?id=542958419109491

@flibbertigibbet any other ideas?

**Comment by CorynWolk** [comment]
I fixed the url thing and set the app to live, so it works now. Could someone with more knowledge of Facebook apps look over the back end to make sure everything needed is enabled/set/filled in? It definitely -works-, but I can't tell if it's now complete.

**Comment by flibbertigibbet** [comment]
Just tested it out, and looks good to me.
