### ISSUE TITLE
Head tag for GPG needs to say Clean Air Council

### ISSUE THREAD

**Issue by WarkulwizDesign** [azavea/cac-tripplanner#427]
The head tag for the GPG site should not say Warkulwiz Design Associates and A+L Development, it should say Clean Air Council. I'm guessing this is leftover from the interim > live site. If you need updated body tag information, let me know and I can send copy from our press release/brochure. 

![screen shot 2015-06-30 at 1 24 20 pm](https://cloud.githubusercontent.com/assets/12275457/8437195/80cf94ee-1f2b-11e5-9744-ec2ec38644fa.png)

**Comment by jbranigan** [comment]
This is leftover from Facebook indexing and will update within a day or so.

**Comment by WarkulwizDesign** [comment]
Ok - perfect. Thanks, John.

On Tue, Jun 30, 2015 at 2:27 PM, jbranigan <notifications@github.com> wrote:

> This is leftover from Facebook indexing and will update within a day or so.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/cac-tripplanner/issues/427#issuecomment-117291935>
> .
>



-- 
*Emily Zuwiala*
Graphic Designer
Warkulwiz Design Associates
89 E Wynnewood Road
Merion Station, PA 19066
215.988.1777
www.warkulwiz.com
