### ISSUE TITLE
Gophillygo.org verified as a Google+ Business

### ISSUE THREAD

**Issue by WarkulwizDesign** [azavea/cac-tripplanner#428]
In order to link the GPG Ad Words business account to the other Google applications, we need to get to www.gophillygo.org verified as our Google+ business website. Attached is a screenshot of the directions. To get there, you'll need to log into Google+ using theadmin@gophillygo.org acct. and go to "Pages" in the left drop-down menu. Then follow the prompt at the top of the Google+ page to find these verify methods. There are five different ways. For some reason, the Google Tag Manager option isn't working for us.
u: admin@gophillygo.org

Ideally, we'd like this to get set up as soon as possible since it affects when we can launch our online ad campaign with Google. Let me know what your timeline is looking like and we can work together to make it work. 

![image](https://cloud.githubusercontent.com/assets/12275457/8438621/03e305a6-1f35-11e5-9ddf-13840a3657eb.png)

**Comment by jbranigan** [comment]
I just edited that post to remove the password posted in clear text. You want to change that password now.

**Comment by jbranigan** [comment]
Please download the HTML file, zip it up, and email it to me. We'll get it uploaded to the site.

**Comment by jbranigan** [comment]
My team just let me know that it would be easier to verify via the domain provider so we don't need to redeploy the servers. If you click the "Alternative methods" tab, there are directions. Also: https://support.google.com/webmasters/answer/176792?hl=en
