### ISSUE TITLE
JotForm attempting and failing to connect to Facebook

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#432]
Seeing console error on deployment homepage.

![image](https://cloud.githubusercontent.com/assets/960264/8478474/aec1e562-209f-11e5-934e-225e3dcea326.png)

This console error does not appear on beta.  Perhaps misconfigured domain for the form? It's unclear why an email contact form should attempt to connect to Facebook.

**Comment by flibbertigibbet** [comment]
Note that the site loads Facebook javascript, and makes heavy use of jQuery (with which JotForm conflicts).

**Comment by jbranigan** [comment]
@flibbertigibbet Is this something that needs to be fixed? I don't see that console error, and the form submission works.

**Comment by flibbertigibbet** [comment]
Console error is gone now; maybe the form configuration got fixed.
