### ISSUE TITLE
Green Ln Reservoir - name in database but won't create directions, only exact address works

### ISSUE THREAD

**Issue by CorynWolk** [azavea/cac-tripplanner#436]
This is one of a few issues flagged by an outside user of the site.

Green Lane Reservoir pops up as a destination option (and it is within GoPhillyGo’s scope), but if you select it, you get an error message. Entering the exact street address of the park instead allows you to plan a trip, and the park is within GoPhillyGo’s boundaries, so you should be able to plan a trip with just the park name.

**Comment by jbranigan** [comment]
I cannot reproduce this. Are there more details?

**Comment by CorynWolk** [comment]
Hi John,

If you start typing Green Lane Park, you get 3 different options in the drop-down. Two just have the name and no address besides the town; one has the name and street address (however, that street address leads to a point outside the park in Google Maps and an error in GoPhillyGo).

![gophillygo green lane try 4](https://cloud.githubusercontent.com/assets/12202740/9045427/124e144c-39f1-11e5-829b-a7755bdf4799.png)
![gophillygo green lane try 3](https://cloud.githubusercontent.com/assets/12202740/9045428/124e6c1c-39f1-11e5-8567-421af1acf51b.png)
![gophillygo green lane try 2](https://cloud.githubusercontent.com/assets/12202740/9045430/1252d892-39f1-11e5-84d7-97fb1403b0ce.png)
![gophillygo green lane try 1](https://cloud.githubusercontent.com/assets/12202740/9045429/12514b9e-39f1-11e5-8851-8ff5807609e9.png)

 If you just type in the correct address for the park (2144 Snyder Rd, Green Lane, PA 180540), you can get directions. 
![gophillygo green lane success](https://cloud.githubusercontent.com/assets/12202740/9045435/1a54e68e-39f1-11e5-8e48-d6968634ef47.png)

This issue might just be as simple as correcting the address for the park in the database, but I'm curious as to why the query produces so many similar options, none of which result in directions.

**Comment by flibbertigibbet** [comment]
The only addresses coming from a database in the app are those for the featured locations, which you can edit in the administrator interface.  The rest come from ESRI's geocoder, which we cannot control.

**Comment by CorynWolk** [comment]
All right. Based on my trial with Google Maps, it looks like the reason I was getting an error message for nearby addresses (Hill Road in Perkiomenville) is because I had selected transit + biking, and there isn't transit near those addresses. Biking only works.
