### ISSUE TITLE
SEPTA + bike directions: bus trip overshoots trail entry, makes trip longer distance (but shorter time?)

### ISSUE THREAD

**Issue by CorynWolk** [azavea/cac-tripplanner#437]
This is another issue flagged by an outside user.

The user noticed this route from Philadelphia to a point along the Perkiomen Valley Trail skirts the trail, even when in “Safer” mode for bike directions. (The exact destination was: Spring Mount Rd, Lower Frederick Twp, Pennsylvania, 19473.) This is mainly because of the bike + SEPTA mode—bike-only directions do incorporate the Trail. However, the reason the bike + SEPTA mode doesn’t incorporate the Perkiomen Trail is that you overshoot the trail by bus. I assume there is a stop closer to the trail that would both allow the user to bike along the trail instead of the road for a shorter trip (as it’d be a shorter distance). I’ve noticed this on other routes planned, too. What causes the system to plan itineraries that overshoot and double back? Is it just because the extra bus time + shorter bike time is a shorter overall duration than less bus time + longer bike time even though the overall distance is longer? (I think I have seen this on bus-only trips as well, though, in which case the bike speed explanation doesn't fit.)
![gophillygo perkiomen trail overshoot](https://cloud.githubusercontent.com/assets/12202740/8532047/8b7b34ca-23f9-11e5-8543-8196fcd8490c.png)

**Comment by jbranigan** [comment]
Yes, this is trip-time related. There may be a way to force this, but it may have consequences for other trip types as well. I recommend that we go with this the way it is.

**Comment by CorynWolk** [comment]
That makes sense. I guess it's like how Google Maps will tell you to bike extra blocks rather than walk your bike a block down a one-way street--annoying but easy for a human to override/ignore en route.
