### ISSUE TITLE
Format for NJ Transit stop entries

### ISSUE THREAD

**Issue by CorynWolk** [azavea/cac-tripplanner#439]
The user tried to enter Pennsauken Transit Center and didn’t get any results. Entering “NJ Transit – Pennsauken” worked fine. I don’t think this is a major issue, or possibly an issue at all, but I figured I'd ask: is it possible to add the format in which the stop’s name is written first as an option for NJ Transit stops in addition to the “NJ Transit – [x]” format? (e.g. "Pennsauken Transit Center" instead of "NJ Transit - Pennsauken")

**Comment by jbranigan** [comment]
This is something that is coming from Esri's geocoder. There isn't anything we'll be able to do here.
