### ISSUE TITLE
Starting location wrong in shared directions

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#444]
I used the share function to get a link for the directions I created. It works fine on my computer, but on anyone else's (I attached my phone as an example) it shows it starting at City Hall, which is wrong, followed by correct directions. 

Sidenote, I had mentioned this previously but that "osmnode" thing is another weird part of the shared directions that happens frequently.

Correct: 
![image](https://cloud.githubusercontent.com/assets/12200440/9468852/e32fd5b0-4b11-11e5-8f57-dba01ed538bc.png)

Incorrect:
![image](https://cloud.githubusercontent.com/assets/12200440/9468807/877bf104-4b11-11e5-8b85-dfd7de0f153b.png)

**Comment by jbranigan** [comment]
Thanks for letting us know, @nickrogers. We'll take a look at this.

**Comment by flibbertigibbet** [comment]
If the browser used to view shared directions has already been used with the app, the origin last used on that browser will appear in the shared directions, instead of the origin sent with the shared directions.
