### ISSUE TITLE
Unable to unpublish articles

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#455]
Logged in as an admin, we are getting error messages when trying to unpublish old articles.

**Comment by jbranigan** [comment]
Nick, can you provide one of the articles you want to unpublish? We can test with that and see what's going on - just don't want to mess up a good post.

**Comment by nickrogers** [comment]
Greenfest and the multimodal happy hour

**Comment by jbranigan** [comment]
Nick, here are two work-arounds:
* You can delete posts using the delete button at the bottom of the edit page. I did this with the Greenfest post (I hope you didn't intend to keep it - we can dig into a backup if needed)
* You can set the publish date far into the future. I did this with the multimodal happy hour - set it to 2026.

We can look into the server error, but are pretty slammed with other projects at the moment. If the workarounds are reasonable, I'd prefer if we could use them.

**Comment by nickrogers** [comment]
We can pause on it at the moment, I'll probably stick to the second option.
How much of a pain is it to dig up the deleted Greenfest post? I would like
to keep it so we can repost it each year when Greenfest comes up.

**Comment by jbranigan** [comment]
Shoot, my bad. I'll try to get that item restored.
