### ISSUE TITLE
discover places not working

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#472]
![image](https://cloud.githubusercontent.com/assets/12200440/16692855/a0473e7a-4500-11e6-934a-d620cbd7aded.png)

just loading forever. Once I got it to finish loading and said "no destinations found"

**Comment by flibbertigibbet** [comment]
Seems to be functioning properly. I do see the address in the screen shot above is not a geocoder result.

![image](https://cloud.githubusercontent.com/assets/960264/16699570/df78ba8e-4522-11e6-9dd8-2bd5d60a0a2e.png)

**Comment by nickrogers** [comment]
This happens if I select a destination from the homepage as well.

**Comment by nickrogers** [comment]
or, it was anyway. Also, that address was one that I had selected from the drop down list.
