### ISSUE TITLE
Map not appearing on back end

### ISSUE THREAD

**Issue by EReinhard** [azavea/cac-tripplanner#489]
I logged in the back end of GoPhillyGo to update a featured destination Tookany/Tacony-Frankford Watershed Partnership's location. However, the map where you can drag the pin is not appearing. Even though I can type in a new address for the location, the location of the destination on the front end of the website does not move. 

![backend map not working](https://cloud.githubusercontent.com/assets/21045113/17677907/cf1ce6ee-6302-11e6-8dc0-0fe2a65c2896.png)

**Comment by jbranigan** [comment]
Error:
```Refused to load the script 'http://openlayers.org/api/2.13/OpenLayers.js' because it violates the following Content Security Policy```

Needs to change to https?
