### ISSUE TITLE
Update OSM to include Sullivan's Bridge 

### ISSUE THREAD

**Issue by jbranigan** [azavea/cac-tripplanner#491]

**Comment by flibbertigibbet** [comment]
Going out in next deploy. The bridge is in the current OSM data, and routable via OpenTripPlanner:
![image](https://cloud.githubusercontent.com/assets/960264/17988264/1fccd692-6af3-11e6-81d7-27326ae00817.png)

**Comment by flibbertigibbet** [comment]
Deployed
