### ISSUE TITLE
Directions default to "arrive by now"

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#509]
Which of course isn't actually possible. Notice the time on my screenshot, it's about 10 oclock and the directions tell me to leave a half an hour ago in order to get there by now.

![image](https://cloud.githubusercontent.com/assets/12200440/18957251/6f6241ca-862c-11e6-8c85-bf4edc5f4cf9.png)

**Comment by flibbertigibbet** [comment]
It defaults to 'departing at', but if you've planned a previous trip in the browser with 'arrive by' set, 'arrive by' gets preserved in the browser's cache (local storage). We should either not preserve the 'arrive by' setting, and also modify the default date/time to something sensible in the future when 'arrive by' is selected.
