### ISSUE TITLE
Redesign for Handlebars places template

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#536]
Apply redesign prototype styles to handlebars template for places cards.

**Comment by flibbertigibbet** [comment]
Awaiting new style for place in the sidebar.

**Comment by lederer** [comment]
Place cards in the sidebar are the same as in the Home view. If an origin is set, they have an green "time · distance · mode" component.

https://marvelapp.com/30a0g54/screen/16895442
