### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#549]
Our coworker here just had an idea that I thought was worth consideration. We have an info@gophillygo.org email that people can contact us on, but it is kind of buried on the site now. Perhaps this is something that could be included on the bottom of every set of directions, with a prompt like "Were these directions useful? Were there issues with your route? Copy the url for your trip and send us feedback at info@gophillygo.org." I realize that many issues will be either individual preferences, or issues with openstreetmap, but it will still be helpful to gather this information, and address the issues we are capable of (including errors in openstreetmap if those come up).

**Comment by jbranigan** [comment]
Sounds good. We'll work this into the design.
