### ISSUE TITLE
Wire up About page

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#555]
Redesign of About page linked to from bottom of home page.

**Comment by KlaasH** [comment]
@lederer two small questions about this:

1. What should the URL be?  The existing one is `/info/about/`.  Other options would include `/about/` or `/learn/about/`.

2. Should the Learn tab header be active when we're on this page, or should no tab be active?  Right now we're passing a `tab` variable to the template that sets the body class and activates the tab in the header.  The prototype for the About page uses `body-info`, same as the Learn pages, but shows none of the tab headings as active.

Bonus question: is the FAQ gone for good?

**Comment by lederer** [comment]
1. I think the URL should be `/about/`

2. None of the tabs should be active when on the About page. It's… special.

3. Yeah, I think if that particular FAQ page is still needed after a redesign, we've done something wrong. :)
