### ISSUE TITLE
Control size of article cards

### ISSUE THREAD

**Issue by KlaasH** [azavea/cac-tripplanner#570]
The article cards are supposed to be a certain size and show what content fits, with `text-overflow: ellipsis;` for the rest (see https://github.com/azavea/cac-tripplanner/pull/566#issuecomment-257011837), but when I try to limit the size of `preview-card` the card itself obeys but everything else just spills out the bottom.  Possibly I'm making an obvious error, or possibly I don't know how flexbox works.  Or both.  Anyway, punting for the moment.

Note also that the article card is used on both the Learn list view and the home page, where it also needs to show the yellow "More tips, ..." link below the chunk of text.

![long_card](https://cloud.githubusercontent.com/assets/6598836/19862312/2ac48a7a-9f66-11e6-804d-fc477b61c18f.png)

**Comment by jbranigan** [comment]
@lederer Might be able to help out here

**Comment by KlaasH** [comment]
PR #582 changed the article cards in a way that makes this not a problem.
