### ISSUE TITLE
Style typeahead input

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#571]
On adding back our autocompleting Typeahead inputs to the home page form, the width of the input box shortens and there's no solid background for the dropdown of suggestions.

![image](https://cloud.githubusercontent.com/assets/960264/19864091/2125cf4a-9f6d-11e6-85c2-13015e23dbdd.png)

**Comment by KlaasH** [comment]
Also the smaller version, with its different color configuration (light text against the blue, currently white on white).

![small_directions_form_invisible_text](https://cloud.githubusercontent.com/assets/6598836/19930829/8555f82c-a0e0-11e6-9797-422495c042a9.png)

**Comment by flibbertigibbet** [comment]
Yes, I'm aware. I created #571 for the typeahead styling, which will require design support. Currently working on a branch with fixes enough to make the sidebar functional and the dropdown readable.
