### ISSUE TITLE
Implement 'See Them All' view and link on place detail view

### ISSUE THREAD

**Issue by CloudNiner** [azavea/cac-tripplanner#579]
Not sure if we have a wireframe for this, but presumably it would be a paginated list of destination-card views on a new page.

![cac-see-them-all](https://cloud.githubusercontent.com/assets/1818302/19941862/1dc46446-a108-11e6-863e-db4d8875b8b2.png)

**Comment by flibbertigibbet** [comment]
Closing in favor of #585. (If home page has all places, no need for a separate list view.)
