### ISSUE TITLE
Typeahead dropdown sometimes opens on marker drag

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#601]
Sometimes when the destination address updates after destination marker drag, typeahead selection drop-down opens on the destination form field.

**Comment by CloudNiner** [comment]
Do you have a test case that reproduces this? I dragged around for a minute or two but couldn't trigger it.

**Comment by flibbertigibbet** [comment]
It's been intermittent. Has only happened for the destination field for me, for some reason (not origin).

**Comment by flibbertigibbet** [comment]
Seems like it only happens after navigation from home view; once typeahead first dismissed on map page, it doesn't pop up again.

**Comment by flibbertigibbet** [comment]
Happens with either origin or destination field if field has focus at time of marker drag.

**Comment by flibbertigibbet** [comment]
This actually happens on `develop` as well, but isn't as noticeable as the origin/destination field doesn't have focus by default on map page load.
