### ISSUE TITLE
Bike mode option broken

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#608]
Picking the bike mode option selector results in a trip plan error.

**Comment by flibbertigibbet** [comment]
Because query sends `optimize` parameter, but without the values to optimize for (safety/speed/flatness). Likely related to #589.

**Comment by KlaasH** [comment]
I don't think this this depends on stored user preferences to work.  In `CAC.Control.Directions.planTrip` it's trying to read the value of the bike triangle interface element
```
var bikeTriangleOpt = $('option:selected', options.selectors.bikeTriangleDiv);
var bikeTriangle = bikeTriangleOpt.val();
$.extend(otpOptions, {optimize: 'TRIANGLE'},
         modeOptionsControl.options.bikeTriangle[bikeTriangle]);
```
So reimplementing the trip options (and modifying the selectors/code as necessary) should suffice, as long as there's a default value for the bike triangle option.  Or we could implement a default some other way, like have the lookup in `modeOptionsControl` be a function that returns the values for 'neutral' if given an undefined `bikeTriangle` value.

**Comment by flibbertigibbet** [comment]
The default value for the bike triangle gets set from user preferences, though you're right that if there is no element to read it back from, the user preferences default doesn't matter.
