### ISSUE TITLE
Implement new itinerary messages

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#614]
There will be a new banner style for the messages that may appear at the top of the itinerary details, such as the message containing transit agency bike policy information link.

Replace existing banner with new design.

**Comment by CloudNiner** [comment]
Is this design finalized? I don't see it anywhere in the marvelapp or the prototype?

**Comment by flibbertigibbet** [comment]
No, I don't think we have it yet.

**Comment by jbranigan** [comment]
Looping in @lederer

**Comment by lederer** [comment]
Is there an example in the current product I can take a look at? 

And what do we know about the contents of the message? Eg, will it have structure (say, title and body) or just a monolithic string? Might it contain images or rich text (other than links, which were already mentioned)? Is there a length limit or expectation?

**Comment by jbranigan** [comment]
The usual message contents are when you book a trip with bike + transit. Once or twice, SEPTA had issues, so we included some more info. 

This trip crosses multiple transit operators.
![image](https://cloud.githubusercontent.com/assets/1508618/20325226/c36305a8-ab51-11e6-93e5-2107347c7913.png)

**Comment by flibbertigibbet** [comment]
You can see the current transit agency bike policy message at the head of the step details for any trip with bike + transit. Example [here](https://gophillygo.org/map/directions?origin=39.9088115%2C-75.2838771&originText=Willows%20Ave%20%26%20MacDade%20Blvd%2C%20Collingdale%2C%20Pennsylvania%2C%2019023&mode=TRANSIT%2CBICYCLE&destination=39.9560539%2C-75.1611169&destinationText=Race%20St%20%26%20N%20Clarion%20St%2C%20Philadelphia%2C%20Pennsylvania%2C%2019107).

We'd just used Bootstrap alerts previously, which gave us the link styling. We also used the alert for the rail contingency schedule until that got resolved, and linked to SEPTA's page on the current status. So generally, just a text snippet with maybe a link is what we use the alert for.

**Comment by CloudNiner** [comment]
Looking at the current map page, theres a banner with a close 'X' in dark blue. Was this intended to be the banner alert described by this issue?

![cac-banner-notice](https://cloud.githubusercontent.com/assets/1818302/20350354/a2191910-abdc-11e6-96a3-f4dd85e5865c.png)

**Comment by lederer** [comment]
@CloudNiner Nope, that banner is higher up in the hierarchy. It's effectively fixed (though not via `position: fixed`) and hence its presence affects the flexbox mojo we use to make this view responsive. 

I think the banner we're talking about will be an inline (or more accurately `static`) element of the Directions content itself, and will scroll with it. Some benefits of this approach:

- We won't have to accommodate yet another conditional to maintain the somewhat fragile flexbox mojo.
- Minimal hierarchical or visual confusion between the two banners.
- The message will be directly associated with these specific directions.

Quick mock:

![image](https://cloud.githubusercontent.com/assets/128699/20352135/3f5b04fc-abe4-11e6-81c0-74f763c45ad0.png)

The internal structure of the component is the same as the current product, except for the NOTICE heading. Do you folks mind building it and taking a pass at styling it like that? I can do some follow-up polish.

**Comment by flibbertigibbet** [comment]
Closed in #648.

**Comment by flibbertigibbet** [comment]
#648 only added bicycle alerts, which use their own, separate template.
