### ISSUE TITLE
BCycle integration - server setup

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#627]
Add JSON configuration file for OTP server deployment in development and production to fetch from BCycle, using project's BCycle API key.

Can be tested by querying for directions using the BICYCLE_RENT mode (which can be used in conjunction with other modes.) If bike share used for the route, there will be a pickup and drop-off station listed in the results, indicated by a `vertexType` of `BIKESHARE`.

**Comment by CloudNiner** [comment]
@flibbertigibbet has API key

**Comment by flibbertigibbet** [comment]
Key has been shared with team
