### ISSUE TITLE
Trip options modal

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#629]
Wire up a trip options modal for when overflow icon clicked, including options such as departure/arrival time, bike optimization options, and the like. Should fix #608.

**Comment by lederer** [comment]
This should be in `src/prototype/extras.html` (demoable at http://localhost:3000/extras.html if you run `grunt` in the `prototype` directory). Holler if that's insufficient or if I misunderstand the issue.

**Comment by flibbertigibbet** [comment]
I'm seeing several modals for different subsets of options, but haven't been able to find the modal that should open initially, from which the user can navigate to the other modals. In the prototype it goes straight to 'bike options' right now.

**Comment by lederer** [comment]
That's the idea. When the mode picker is in Bike mode, clicking the options button should open the Bike Options modal. From there, the user can click into indego, timing, or ride quality modals.

Similarly, when the mode picker is in Walk mode, clicking the options button should open the Walk Options modal. From there, the user can click into timing or accessibility modals.

**Comment by flibbertigibbet** [comment]
@lederer: When is this options menu:
![image](https://cloud.githubusercontent.com/assets/960264/20673460/3e406bde-b553-11e6-94f6-34999af02857.png)

supposed to be shown, and when this menu with selected values?
![image](https://cloud.githubusercontent.com/assets/960264/20673521/67f1e46c-b553-11e6-8d73-7a92b0e953ff.png)

**Comment by lederer** [comment]
@flibbertigibbet: Pardon the ambiguity. Each of those appears when the user clicks the options button while in Bike mode. The decision of which to show comes down to how many options are currently set:

- If *no* options are set, show the first one. This is the default case.
- If *all* options are set, show the second one.
- If *some* options are set, render those options as "selected" and the other options as unselected.

To be thorough, these menus also appear when the user is done interacting with an options submenu. So for example, say the user clicks the options menu (while in Bike mode) and gets that first menu with all items unselected. They click the "Indego bike sharing" item and so the Indego submenu appears. Then they click one of the options in that submenu. At that point, this menu reappears, with the Indego item in selected mode, and the other two items unselected.

There is also a corresponding menu for when the app is in Walk mode, which works by the same logic above.

Holler if unclear and I'll swing by.
