### ISSUE TITLE
Wire up bike share option in UI

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#630]
Wire up UI components for selecting and routing via Indego bike share.

Depends on #627 and #629.

**Comment by lederer** [comment]
This should be in `src/prototype/extras.html` (demoable at http://localhost:3000/extras.html if you run `grunt` in the `prototype` directory; scroll to the bottom of the page). 

Holler if that's insufficient or if I misunderstand the issue.

**Comment by flibbertigibbet** [comment]
Closed in #662
