### ISSUE TITLE
Bike share specific directions

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#631]
Modify itinerary summary and step-by-step directions results for bike share to use Indego icon and include information on picking up and dropping off bike.
Depends on #630.

**Comment by lederer** [comment]
This should be in `src/prototype/extras.html` (demoable at http://localhost:3000/extras.html if you run `grunt` in the `prototype` directory; scroll to the bottom of the page). 

Holler if that's insufficient or if I misunderstand the issue.
