### ISSUE TITLE
Update Indego map pin

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#632]
There's a new font icon for Indego bike share; not sure if we should be using that on the map as well. If so, we'll want to have that as a .png.

Currently:
![image](https://cloud.githubusercontent.com/assets/960264/20409373/56035ec6-ace7-11e6-8ba9-422e4f80985b.png)

**Comment by lederer** [comment]
Let's stick with the existing .png for the map marker. 

Whereas we'll use the font icon for inline textual / off-map contexts.
