### ISSUE TITLE
Missing bike icon in steps list when transitioning from walking

### ISSUE THREAD

**Issue by KlaasH** [azavea/cac-tripplanner#645]
The first itinerary [biking from Fairmount Waterworks](http://localhost:8024/?origin=39.965811%2C-75.183494&originText=Fairmount%20Waterworks%20Interpretive%20Center&mode=BICYCLE%2CTRANSIT&destination=39.9616133%2C-75.1541914&destinationText=990%20Spring%20Garden%20St%2C%20Philadelphia%2C%20Pennsylvania%2C%2019123) never shows a bike icon.  After "arrive path" there should be a step saying to set out by bike, but it goes right to a turn step.

![no_bike_icon](https://cloud.githubusercontent.com/assets/6598836/20444911/f5d60bd8-ada0-11e6-89c2-70d3fcf260b2.png)

**Comment by flibbertigibbet** [comment]
This appears to be due to removing the leg header section, which has the mode type information. Comparing with current production:
![image](https://cloud.githubusercontent.com/assets/960264/20493618/97f9cdf8-afe7-11e6-80be-581f0be298eb.png)
