### ISSUE TITLE
Make top itinerary "selected" in sidebar by default

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#680]
Repro:
1. Get any directions. One or more itineraries are listed in sidebar.
1. Hover on an itinerary. It becomes selected.
1. Hover away from that itinerary. It does not deselect (until you hover on a different one).

Expected the itinerary to deselect onmouseout, regardless of whether subsequently hovering on a different one).

**Comment by flibbertigibbet** [comment]
That is intentional and specifically implemented to behave that way (select until another selected.)

**Comment by lederer** [comment]
That's okay as long as one of them is selected automatically on render, so that there is never a state when no itinerary is selected (iff >0 itineraries are listed). Can we do that?

Side note: if we're not already doing it, the itineraries should be listed in ranked order, by whatever metric we're ranking them. And hence the preselected itinerary should be the first one listed.

**Comment by flibbertigibbet** [comment]
The itineraries come back from OTP with the best/most efficient first. Currently the first itinerary is highlighted by default on the map; it just isn't highlighted in the sidebar until hover.

**Comment by lederer** [comment]
Oh good. Very little needs changing then. I'll update the issue title.
