### ISSUE TITLE
Bring back directions page

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#696]
The static directions list page to which the social sharing permalinks refer got removed. Bring it back.

**Comment by flibbertigibbet** [comment]
Added back in #693, but it needs styling work:
![image](https://cloud.githubusercontent.com/assets/960264/21067403/02dd4762-be39-11e6-82b8-e48ba3911407.png)

**Comment by lederer** [comment]
Interesting. Hadn't realized this page exists. Seems more fitting as a Print page rather than a Share landing page.

Would it be possible to have the permalinks point to the normal directions page instead (ie, functionally equivalent to copying the URL from the address field)?

**Comment by flibbertigibbet** [comment]
We could redirect the existing directions permalinks to the new map directions page instead. The reason we added it originally was for a mobile-accessible directions view, though that should no longer be necessary with the redesign.

@jbranigan do you know what is supposed to happen with the shareable directions page in the redesign?

**Comment by flibbertigibbet** [comment]
Existing share links should be redirected to map page. Directions page will be left in but unstyled.
