### ISSUE TITLE
Show 24h of depart/arrive timing options when not "Today"

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#698]
Time menu only showing "Now" to 11:45 pm even if I change to a future date.

Repro:
1. Get any directions.
1. Options > Arrive/depart at…
1. Change from "Today" to a future date.
1. Time menu says "Now".
1. Open time menu. Can't choose a time before Now.

Proposed behavior:
- When user changes date from "Today" to a future date, the selected time option should change from "Now" to the next 15-min interval closest to now (eg, 1:15 pm). If the user opens the time menu, it should list all 15-min intervals from 12:00 am to 11:45 pm.

- When the user changes the date from a future date to "Today", the selected time option should remain at whatever it's currently set to — unless it's earlier than now, in which case set it to Now. If the user opens the time menu, it should only list options from Now to 11:45 pm.

**Comment by flibbertigibbet** [comment]
Behaves as described on staging: https://orange.production.web.gophillygo.org

**Comment by flibbertigibbet** [comment]
Have not been able to reproduce on current `redesign`; future dates show full 24-hour time range, and toggling back to 'Today' limits again to no earlier times.

**Comment by flibbertigibbet** [comment]
Okay, have been able to reproduce on Firefox. Looks like also happens on Mac OS+Chrome, but not Linux+Chrome.
