### ISSUE TITLE
Restore/implement higlighting and limiting destinations in Explore sidebar

### ISSUE THREAD

**Issue by KlaasH** [azavea/cac-tripplanner#713]
In the olden days, mousing over a destination in the sidebar would highlight the marker on the map.  I assume that behavior should be restored.

It also appears from the code, but doesn't happen in production, that there was an idea of limiting the list of destinations to ones that are reachable within the given time limit.  This also seems to be the behavior shown in the wireframe: https://marvelapp.com/2he4i01/screen/16206349.  So that should be implemented if it's desired.  If not, it might make sense to add some separation between the destination logic and the isochrone logic.

**Comment by flibbertigibbet** [comment]
Original implementation was to filter to limit to destinations within the isochrone. It got modified to show all instead and ignore the isochrone bounds due to (non-developer) feedback.
