### ISSUE TITLE
Show all destinations on Explore map when no origin set

### ISSUE THREAD

**Issue by KlaasH** [azavea/cac-tripplanner#714]
Related to #713.  If we don't want to limit destinations by what's reachable, then we should just be showing all destinations whenever the Explore tab is active.  If we do want to limit to reachable destinations, then we need to have a codepath that shows all destinations when no origin is set.

**Comment by flibbertigibbet** [comment]
#725 shows all destinations when no origin is set, with the exception of when a geocoding error occurs on the origin while in the explore view, in which case the destinations are hidden to show the geocoding error.

If there is a gecoding error on the explore tab and the user navigates back to the home page via the logo button, the destinations list needs to be reset without trying to get the travel times, which is a separate issue.
