### ISSUE TITLE
Explore tab link behavior

### ISSUE THREAD

**Issue by KlaasH** [azavea/cac-tripplanner#715]
Part 1, a question:
Should the Explore tab link do something different from what the "Map View" button on the places list does, i.e. open the Explore tab, whether or not there's an origin?  My assumption has been no, based on the fact that clicking Explore from https://marvelapp.com/2he4i01/screen/16206347 goes to https://marvelapp.com/2he4i01/screen/16206348.

Part 2, a thing to fix:
On the Learn tab and the place detail view (which is labeled as part of the Explore tab but which is a separate Django view), the tab links are actual links.  The behavior of the Explore tab on the Home view is a javascript action, telling tabControl to activate the tab, but that only works when the Home view is already loaded.  We don't currently have a way to go straight to the Explore tab by link when no origin is set.

One option would be to use the URL router to detect a path or parameter and set the UserPreferences method to 'explore', then clear the URL or parameter.  The Home view checks UserPreferences method on load and goes to the corresponding view if `isDefault` is false.

Doing only that might cause nasty flashing, though, because the body class won't be set in the Django template.  So if there's a way to make a direct link work in Django that would probably be preferable.

**Comment by lederer** [comment]
@KlaasH Re part 1: Correct! The Explore tab link and the Map View button should have precisely the same behaviors, both for when an origin is set and when an origin is not set.

**Comment by flibbertigibbet** [comment]
This is the current (same) behavior.
