### ISSUE TITLE
Show error on isochrone failure

### ISSUE THREAD

**Issue by KlaasH** [azavea/cac-tripplanner#716]
I.e. fix this TODO: https://github.com/azavea/cac-tripplanner/blob/redesign/src/app/scripts/cac/control/cac-control-explore.js#L178

There's an `alert` template that's used for directions errors: https://github.com/azavea/cac-tripplanner/blob/redesign/src/app/scripts/cac/control/cac-control-itinerary-list.js#L69

**Comment by flibbertigibbet** [comment]
Relatedly, the message for failed trip plan should go in an alert instead of just sitting in the sidebar.

![image](https://cloud.githubusercontent.com/assets/960264/21357179/458425ce-c6a2-11e6-9f68-6f0ac142db23.png)

The styling for this at least should have gone in the fix to #614.
