### ISSUE TITLE
Indego option not working?

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#751]
REPRO:
1. Get biking directions between locations near Indego stations. Eg from [990 Spring Garden St, Philadelphia, Pennsylvania, USA] to [W Girard Ave & N 3rd St, Philadelphia, Pennsylvania, 19123].
1. Now turn on Indego.
1. Expected Indego directions. Got walking directions instead.

**Comment by flibbertigibbet** [comment]
works for me on staging:
![image](https://cloud.githubusercontent.com/assets/960264/22214924/887bffb6-e167-11e6-9aaa-9f6344cd8668.png)

Note that using an ampersand in an address isn't valid with the ESRI geocoder, so the destination address in the issue isn't valid. Also, would need to check if bikes/slots are available at the nearby stations. If not, walking directions would be correct.

**Comment by lederer** [comment]
Doh. Turns out it works for me on staging too, just not locally. Shoulda checked their before filing the issue. :)
