### ISSUE TITLE
Recursive markup on learn page?

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#755]
There's a bit of chaos on the Learn page. Here's one example from staging:
![image](https://cloud.githubusercontent.com/assets/128699/22219929/acf819de-e17a-11e6-964a-43e2954b97e1.png)

I suspect this is due to recursively nested `a.preview-card-link` tags in the produced markup:
![image](https://cloud.githubusercontent.com/assets/128699/22219910/9e34c5b4-e17a-11e6-9f03-8cd46c4745cb.png)

Not sure why that's happening. IIUC it should *just work* [TM] if the DOM is structured per [learn-index.html](https://github.com/azavea/cac-tripplanner/blob/redesign/src/prototype/app/learn-index.html) in the prototype, though I'll probably end up eating my words.

**Comment by lederer** [comment]
On mobile, the Learn page can be horizontally scrolled (it shouldn't). I'd bet it's due to this, so once it's fixed we should confirm that.

![img_1235](https://cloud.githubusercontent.com/assets/128699/22220236/d7205f86-e17b-11e6-996c-0cec3c28a112.PNG)

**Comment by flibbertigibbet** [comment]
Could you provide some steps to reproduce? Not seeing this on staging or locally right now; tried clicking around.

**Comment by flibbertigibbet** [comment]
Cannot reproduce locally

**Comment by lederer** [comment]
The horizontal scrolling may have been fixed by a commit I did yesterday, but the overall "chaos" mentioned in the initial comment is still there.

Repro:
1. Go to https://staging.gophillygo.org/learn/ (I'm on Chrome 55/Mac).
2. Scroll down to see most content flowing outside its containers.
3. Examine the DOM. Some of the `.preview-card` elements have multiple `a.preview-card-link` elements nested at various levels within them. But I think there's supposed to be only one `a.preview-card-link` per `.preview-card`.

**Comment by flibbertigibbet** [comment]
Visible on staging but not _locally_.

**Comment by lederer** [comment]
Ah, ok. Great. The Learn articles don't render on my local machine, so I've only seen it on staging. Good to know it's fixed.

**Comment by flibbertigibbet** [comment]
Not sure if it's fixed, but hopefully not reproducible because of some change since the last staging push that did fix it. Also possible it's related to some difference in the entered place data, though I took a look and nothing popped out.

**Comment by flibbertigibbet** [comment]
Still visible on staging after yesterday's update

**Comment by flibbertigibbet** [comment]
Copy-paste of article information from the staging `admin` interface produces same appearance. Issue appears to not be with our code exactly, but with the current content posted, which has a lot of rich formatting. The WYSIWIG editor appears to have produced a lot of extra junk HTML for it.

**Comment by flibbertigibbet** [comment]
@lederer can you modify layout to contain the current article content? Happy to help with reproducing.

**Comment by lederer** [comment]
@flibbertigibbet Yup will do.

**Comment by lederer** [comment]
Sorry for rehashing old ground, but I'm still confused by what's happening here. 

Here's the structure of the card from `partials/article-card.html`:

```html
<div class="preview-card">
    <a class="preview-card-link">
        <img class="preview-photo" />
        <div class="preview-details">
            <div class="category-heading"></div>
            <h2>{{ article.title }}</h2>
            {{ article.teaser|safe }}
        </div>
    </a>
</div>
```

Note there's a single `a.preview-card-link` that wraps the entire content inside `div.preview-card`, and there is no logic for iterating, looping, repeating, or recursion.

Meanwhile, here's the DOM on staging for the "Video Trip to SCEE" article card:

```html
<div class="preview-card">
    <a class="preview-card-link">
        <img class="preview-photo">
    </a>
    <div class="preview-details">
        <a class="preview-card-link">
            <div class="category-heading"></div>
            <h2>Video Trip to SCEE</h2>
        </a>
        <p>
            <a class="preview-card-link">
                Watch the video here:&nbsp;
                <br>
            </a>
            <a href="https://youtu.be/ZTKbLrG36hg" target="_blank">https://youtu.be/ZTKbLrG36hg</a>
        </p>
    </div>
</div>
```

Here there are three `a.preview-card-link` elements instead of one. One wraps `img.preview-photo`. One wraps the first two children of `div.preview-details` — the category and title. And one wraps some of the text within the `<p>` output by `article.teaser|safe`.

I'm mystified that `a.preview-card-link` is being replicated within the article content like that. I'm happy to stick a `<div>` around the output if that will fix it. But this seems more complex than that, no? Those links shouldn't be making it into the output in the first place.

**Comment by flibbertigibbet** [comment]
Issue is that the summary card template wraps the title and teaser in an anchor tag, while the WYSIWIG editor allows rich content (including links and arbitrarily long text) in the teaser field.

As embedded anchor tags are illegal HTML, teaser links break the template; also the long teasers overflow the provided space.
