### ISSUE TITLE
Geolocation progress indicator

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#764]
When the user clicks the geolocate button, we should indicate that it's working on it.

I've added some sass to spin the geolocate button itself. Let's start with that, and if it ends up being silly, I'll replace the compass icon with a more traditional spinner while in that state.

To enable this, add the `.spin` class to `.btn-geolocate` when the geolocation process begins. And remove it when it ends.

**Comment by flibbertigibbet** [comment]
One wrinkle to this is that the geolocation request might fail, as happens randomly.

**Comment by lederer** [comment]
Can we know the failure happened, via an error or even a manual timeout? If so we can still remove the `.spin` class when the process ends (ie, fails), and then alert the user it failed.

I forget, do we have an existing system for rendering alerts/notifications? If not, even a plain old JS alert dialog would be acceptable for now.
