### ISSUE TITLE
Add geolocate button to mobile map?

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#799]
Mobile maps usually have a geolocate button. [We had one in the mocks](https://marvelapp.com/2b7784h/screen/14699152) but it got lost along the way.

**Comment by flibbertigibbet** [comment]
Isn't this part of the next phase proposal?

**Comment by lederer** [comment]
Don't know. If it is, no problem. Feel free to close or otherwise triage this issue.

**Comment by flibbertigibbet** [comment]
Closing for #835
