### ISSUE TITLE
Drag origin interpreted as drag destination

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#815]
Repro:

1. Get directions from any origin to any destination. Mode doesn't matter.
1. Drag the *origin* to a new location.
1. The resulting directions retain the old origin and move the destination to the dropped location, instead of retaining the old destination and moving the origin.

**Comment by flibbertigibbet** [comment]
Result of #789 styling change that modified marker title for origin. Marker title used to determine which marker was dragged.

**Comment by lederer** [comment]
Ah, interesting. Is there a different attribute that can be used to determine which marker was dragged?

**Comment by flibbertigibbet** [comment]
Looking into it, will figure something out. Title isn't the best thing to use anyways.
