### ISSUE TITLE
Itinerary summaries: One transit icon to rule them all

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#816]
Currently the itinerary summary includes icons for each mode of the trip, including specific transit modes. This can get a little out of hand:
![image](https://cloud.githubusercontent.com/assets/128699/22595828/15de96d8-e9f7-11e6-98d5-131a49403881.png)

We should use a single transit icon in the summaries to simply indicate that the itinerary involves transit. 

This change would apply only to the summary panels, not to the step-by-step directions.

**Comment by flibbertigibbet** [comment]
Done in #859
