### ISSUE TITLE
Hero images are blurry and cropped wrong

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#822]
From client:

>The photos are all the right size - I know because they won't upload if they are even one pixel off! The larger photos (once you click more info) are pretty much all out of focus (even though they look fine offline). We've also tried loading higher quality photos but they were rejected because the file size was too big. Some of these are cropped wrong too (see the multimodal happy hour as a destination). Again, that's not how it looks offline.

The blurring appears to be due to the small/large images being swapped. I.e., we're serving the large image where the small should be, and vice versa.

- [x] Swap large/small images

The cropping issue should be resolved automatically when the above is fixed. But we should also center those images to be safe.

- [x] Center hero images

/cc @jcahail @flibbertigibbet

**Comment by lederer** [comment]
Cropping/positioning issue handled in #823.

**Comment by flibbertigibbet** [comment]
Sizes were implemented as specified in #795; "narrow" is now "small" and "wide" now "large". Where are these "swapped" in presentation? For destinations, articles, or both? Summary or detail view? In map sidebar list? Please provide fix on this PR, and images to test.

**Comment by lederer** [comment]
Looking at staging… 

Article imagery seems fine, in all contexts. This issue applies to destinations. 

All small destination images (cards on home page, cards in explore sidebar, cards at bottom of place detail page) are actually using the large image assets (640x400). They are shrunk to fit. The aspect ratios are different, so they look bad (though at a glance it's easy to miss).

Similarly all large destination images (the hero image at the top of the place destination page) are using the small image assets (310x155), so they're enlarged and look terrible.

@flibbertigibbet I'll commit a fix. Holler if I do it wrong.

**Comment by flibbertigibbet** [comment]
Okay, thanks for the details. Fix looks good!
