### ISSUE TITLE
Display total travel times and distances per mode

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#837]
Show total travel time per mode in trip summaries and on detail view.

**Comment by lederer** [comment]
Mocks: https://marvelapp.com/2jh0ge8

/cc @flibbertigibbet @jcahail

**Comment by flibbertigibbet** [comment]
Sub tasks:
- [ ] implement summary in list view
- [ ] implement summary in details view
- [ ] do not display when there is only one mode (no transit)
- [ ] set a minimum threshold for showing a mode type in the summary (i.e., no travel time for a walk under 100 ft)
- [ ] use a single common icon for transit mode(s) in the summary
