### ISSUE TITLE
Enter explore mode when map view destination field becomes empty

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#873]
Repro:
- Get directions, so that you're in map view with an origin and destination
- Clear the destination field
- The destination placeholder now says "Enter a destination – or choose one below"
- … but the area below is blank

![image](https://user-images.githubusercontent.com/128699/28985866-97c18ac8-7932-11e7-80c2-a54b09eadb59.png)

Instead we should enter explore mode (ie, list all destinations, and show them on map) when the destination field becomes empty.

**Comment by flibbertigibbet** [comment]
Wouldn't this leave the user with no way to clear and re-enter the destination? As the explore mode has no destination field.

**Comment by lederer** [comment]
Good point. I'm conflating explore mode (aka travelshed) with listing all destinations, when in fact these should be teased apart…

Currently:
- When in "to" mode with an _empty destination_, we list zero destinations. (Though the placeholder says "…choose one below".)
- When in "within" mode with an _empty origin_, we list all destinations.
- When in "within" mode _with an origin_, we also list all destinations.
   - We list them **all** — even those outside the travelshed — which feels odd because it betrays the distance filter.

Proposed:
- When in "to" mode with an _empty destination_, list all destinations. 
  - If an origin is set, sort the destinations by travel time.
  - This will bring map view into parity with the home view.
- When in "within" mode with an _empty origin_, list zero destinations.
- When in "within" mode _with an origin_, list only those destinations within the travelshed. (Destinations outside the travelshed can still be visible on the map.)

**Comment by flibbertigibbet** [comment]
Depends on #876

**Comment by lederer** [comment]
> (Destinations outside the travelshed can still be visible on the map.)

Idea: Mark all destinations inside the travelshed with large pins and all destinations outside the travelshed with small pins or dots.
