### ISSUE TITLE
To/within toggle not working

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#874]
When in map view, clicking the to/within label next to the destination field has no affect. This occurs regardless of whether an origin is set, and regardless of whether it's currently in "to" mode or "within" mode.

**Comment by flibbertigibbet** [comment]
Cannot reproduce. Could you provide more details?

Note that that "explore mode" has been intentionally disabled for narrow screen widths (see #742).

**Comment by lederer** [comment]
Doh. That explains it. 😳 

Which means the breakpoint we use to disable explore mode (`992px` ) is different from the one we use for snapping into the mobile layout (`480px`).

Those should probably both be `480px`.

**Comment by flibbertigibbet** [comment]
Makes sense. I think that 992px breakpoint may have been used because it related somehow to styling around the explore mode, but maybe we can just swap it out and it will be fine.

**Comment by lederer** [comment]
Yeah. If I follow correctly, it's [only being used](https://github.com/azavea/cac-tripplanner/blob/6693385ec3c3ebb63920b6e4976187d06eebe04e/src/app/scripts/cac/pages/cac-pages-home.js#L63) to determine whether to [showCurrentLocation](https://github.com/azavea/cac-tripplanner/blob/5547086b62399aee15952ba0285ffa19eadf1ce4/src/app/scripts/cac/map/cac-map-control.js#L146). 

Hopefully swapping int the 480px breakpoint will work just fine. 🤞

**Comment by flibbertigibbet** [comment]
In code, it is being used both to determine whether to show current location and whether to show or hide explore mode options.

My concern is not with the code, but rather with the `md-up` breakpoint style rules and if or how they might related to rendering of elements related to explore mode.

**Comment by lederer** [comment]
Looks like we're good to do, as we don't appear to be using `md`, `md-up`, or `md-down` at all.
