### ISSUE TITLE
Travel time by mode- 1 mile or less should be singular

### ISSUE THREAD

**Issue by jcahail** [azavea/cac-tripplanner#885]
Currently displays "1 miles"

![image](https://user-images.githubusercontent.com/24727081/29720638-8d012a24-8988-11e7-977b-3309a3bb31e9.png)

**Comment by flibbertigibbet** [comment]
Due to change in #859 from 'mi' to 'miles.'

Test for and use singular 'mile' if one mile, [here](https://github.com/azavea/cac-tripplanner/blob/develop/src/app/scripts/cac/routing/cac-routing-itinerary.js#L178).
