### ISSUE TITLE
Error saving new destinations in admin panel

### ISSUE THREAD

**Issue by jcahail** [azavea/cac-tripplanner#887]
Nick and Erika are getting the error below when creating new destinations. Both are using Chrome and Windows. 

Nick saw the issue last week when creating Parks on Tap 2. The issue seemed to resolve itself when he cleared his cache. Erika is now seeing the same error when attempting to create a Parking Day destination (on 9/5); she presses save, she gets to an error screen. When she presses back in the web browser, nothing is saved and she has to start over, with nothing ever getting saved. She has cleared her cache and logged out/logged in.

![gophillygo_bug](https://user-images.githubusercontent.com/24727081/30080688-763bfba2-9252-11e7-8ff3-7ec0c8f20524.png)

**Comment by flibbertigibbet** [comment]
Can reproduce locally.

**Comment by flibbertigibbet** [comment]
This does seem to be related to cookies and may be [this issue](https://code.djangoproject.com/ticket/24492). Clearing cookies resolved the issue for me.

**Comment by flibbertigibbet** [comment]
On production, there is also the following service worker related console error:
![service_worker_error](https://user-images.githubusercontent.com/960264/30107739-ea3f567c-92ff-11e7-9c41-5d8c41b2bd25.png)

**Comment by flibbertigibbet** [comment]
I do see changes being saved, despite the error page.
