### ISSUE TITLE
Wrong directions given 

### ISSUE THREAD

**Issue by jcahail** [azavea/cac-tripplanner#890]
CAC staff member reported getting wrong directions from 135 S 19th St, Philadelphia, PA, 19103, USA to 1253 E Palmer St, Philadelphia, PA, 19125, USA, with Indego Bike Share and Safe Route enabled. (Going the wrong way on 15th St.). 
![image](https://user-images.githubusercontent.com/24727081/30754088-58a376d4-9f8f-11e7-9d93-9e0516a84fc8.png)

Bicycle Coalition's map does suggest that 15th just south of Dilworth Plaza is one way going south: http://bicyclecoalition.org/wp-content/uploads/2014/01/Bike-Map-2014_reduced.pdf.

**Comment by flibbertigibbet** [comment]
The directions provided say to walk (biking segments would show in purple, but here are blue; also would have different icon in sidebar). So, the direction of travel is fine for walking.

OpenStreetMap does have S 15th Street marked as one-way, southbound:
![image](https://user-images.githubusercontent.com/960264/30760485-5299c734-9fa8-11e7-9e72-4dea5977b39b.png)

**Comment by flibbertigibbet** [comment]
Closing; see related #891.
