### ISSUE TITLE
Reorder destinations by travel time

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#906]
When an origin is set, sometimes destinations can appear out of order:

![image](https://user-images.githubusercontent.com/128699/31838935-eee37e54-b5ac-11e7-9f64-d5553f2689c5.png)

Per @flibbertigibbet:
> When getting all destinations, the Django app endpoint returns them ordered by distance, which is how they appear. The travel times are queried later, then added in to the card without re-ordering. So it's possible something may be geographically closer but take longer to get there, particularly when using transit.

Would be nice to reorder them, if needed, after the travel times are determined.

See #904

**Comment by flibbertigibbet** [comment]
See #904 for discussion on rationale on why this is not the behavior currently.
