### ISSUE TITLE
Update deployment dependencies

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#914]
Switch to terraform or some other deployment process.

Currently deployment depends on a set of custom scripts (majorkirby) that are no longer maintained, which in turn depend on an outdated version of `troposphere`.

**Comment by flibbertigibbet** [comment]
No urgent reason to switch, but would be good to do so before it becomes an issue.

**Comment by hectcastro** [comment]
Scope of this issue is to ensure that all deployment related dependencies are update and remain in a functioning state:

- Ansible
- Packer
- Troposphere
- Major Kirby
- ...
