### ISSUE TITLE
Investigate formatting issue on Learn page

### ISSUE THREAD

**Issue by jcahail** [azavea/cac-tripplanner#929]
![image](https://user-images.githubusercontent.com/24727081/33617879-f711e658-d9ae-11e7-8b3b-b7f34f37d3a0.png)

![image](https://user-images.githubusercontent.com/24727081/33617915-0cf7ddd8-d9af-11e7-8bab-f123f15cc43f.png)

Nick has cleared his cache, but the issue persists.

**Comment by lederer** [comment]
It only affects items with inline links. They can’t include any links in the summary content that appears on that page. Links should only be used in the longer description on each item’s detail page.

**Comment by flibbertigibbet** [comment]
Also to note, there are a number of images that do not meet the specified dimensions; attempting to re-save an article with images with incorrect dimensions will fail. The images above should not be so tall.
