### ISSUE TITLE
Switch from authbind to nginx proxy

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#950]
~~Some users currently experience authbind not binding to port 80, making the OTP VM inaccessible.~~

Issue apparently was a manifestation of insufficient OTP process memory set.

Remove authbind and instead proxy the `otp` service running on a high port behind nginx. Ensure CORS is enabled.

**Comment by hectcastro** [comment]
We've lost track of this one. Do you still think we should add it?

**Comment by flibbertigibbet** [comment]
No, I'll go ahead and close this.
