### ISSUE TITLE
Replace category tabs with dropdown on home page in narrow viewports

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#952]
Category_tabs on the home page take up too much space in viewports below 768px wide:

![image](https://user-images.githubusercontent.com/128699/34179016-4b1aad56-e4d7-11e7-9f6c-088b5e60d759.png)

We should automatically replace them with the category dropdown menu from the map page under that condition.

Just reuse the exact same `header.places-header` DOM subtree from the map view. I can adjust the styles to ensure they apply to the home page as well.

Connects #951

**Comment by flibbertigibbet** [comment]
Note the existing styles on `develop` support tabs on all screen sizes; screenshot above not reproducible on current `develop`.

**Comment by lederer** [comment]
> the existing styles on develop support tabs on all screen sizes

Hmm. I originally didn't want to shrink the font-size so much, but come to think of it, since we're removing the "Relax" category, we only need to shrink them down to 14px and they fit fine.

I'll push some responsive code to #951 and close this issue. We can revisit if needed.
