### ISSUE TITLE
Category tabs sometimes appear temporarily on map view

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#953]
In at least one scenario, map view displays category **tabs** temporarily before switching to the category **dropdown**.

![image](https://user-images.githubusercontent.com/128699/34179866-903e7d92-e4da-11e7-8ea8-1d0d5a5e421e.png)

Repro:
1. Go to Map view (Explore)
1. Set an origin
1. Expand travelshed if necessary
1. Click "More info" on a place card
1. Click the back button

Connects #951

**Comment by flibbertigibbet** [comment]
Is quickly replaced by loader. Consider displaying loader earlier in sidebar render process.
