### ISSUE TITLE
Remove requirement to select activity on destinations/events

### ISSUE THREAD

**Issue by jcahail** [azavea/cac-tripplanner#954]
Right now, the admin user is required to select both an activity and a category for any newly created destinations or events before saving. While category should be required, activity should not.

![gpg screenshot 12 7 17](https://user-images.githubusercontent.com/24727081/34211515-52102a24-e567-11e7-9e62-3fd5dc4981c0.PNG)

**Comment by flibbertigibbet** [comment]
Category should not be required either (not required on model/DB level).
