### ISSUE TITLE
Keep explore mode sidebar empty when destination already set

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#964]
As @KlaasH observed in #962, if you click "Directions" on a destination on the home page while the origin field is empty, you land on the map with the sidebar empty. This is expected. However, if you (1) wait long enough, or (2) hit a key while focused on the origin field, the sidebar populates with featured destinations.

Since the destination is already chosen, and it's unlikely the user's origin will be a GoPhlGo destination, we should keep the sidebar empty in this scenario.

**Comment by flibbertigibbet** [comment]
Event happening to trigger this is a spurious `clearLocation` call happening to user preferences, even when app just sits.
