### ISSUE TITLE
Rename canoeing activity

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#969]
Make more general, like "water activity"

**Comment by jcahail** [comment]
Per Nick, please change to "water recreation".

**Comment by flibbertigibbet** [comment]
Going to mention @lederer here, in case we should reconsider the icon or layout for the change.

**Comment by lederer** [comment]
I'll take a gander at our icon options.

**Comment by lederer** [comment]
Icon updated in #972
