### ISSUE TITLE
Implement additional activity icons

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#975]
Hiking and water recreation icons added in #972, but currently only icons for accessibility, Watershed Alliance member, and cycling display in the UI; of those only 'cycling' is an 'activity'.

Add logic to display icons for the other activities in the UI.

**Comment by flibbertigibbet** [comment]
@lederer not sure where all these should be used, apart from the detail pages.

**Comment by lederer** [comment]
Correct, they should only appear on the detail page: https://marvelapp.com/59eh08g/screen/35591680

![image](https://user-images.githubusercontent.com/128699/35002895-1745f88a-fab9-11e7-9a42-8b668fce001f.png)
